# -*- coding: utf-8 -*-
"""OpenMedic 名录数据：诺贝尔生理学或医学奖 1901–2025。

DATA = {年份: (获奖理由英文, 获奖理由中文, [(姓名en, 姓名zh, 国籍), ...])}
获奖理由为 Nobel 官方 citation；共享理由年份为全年份共通；拆分理由年份（如
1966 / 1977 / 1981 / 2008 / 2011 / 2015 等）用 "||" 分隔，顺序与获奖者一一对应。
国籍沿用 Nobel 官方 country 口径（Wikipedia 表格 rowspan 合并的串行已修正）。
"""

US = "United States"
UK = "United Kingdom"

DATA = {
    1901: ("for his work on serum therapy, especially its application against diphtheria, by which he has opened a new road in the domain of medical science and thereby placed in the hands of the physician a victorious weapon against illness and deaths",
           "表彰他在血清疗法方面的工作，尤其是其应用于防治白喉，为医学科学开辟了新路，并因此为医生提供了战胜疾病与死亡的制胜武器",
           [("Emil von Behring", "埃米尔·冯·贝林", "Germany")]),
    1902: ("for his work on malaria, by which he has shown how it enters the organism and thereby has laid the foundation for successful research on this disease and methods of combating it",
           "表彰他在疟疾方面的工作，揭示了疟疾如何进入机体，为该疾病的成功研究及防治方法奠定了基础",
           [("Ronald Ross", "罗纳德·罗斯", UK)]),
    1903: ("his contribution to the treatment of diseases, especially lupus vulgaris, with concentrated light radiation, whereby he has opened a new avenue for medical science",
           "表彰他利用聚光辐射治疗疾病特别是寻常狼疮的贡献，为医学科学开辟了新途径",
           [("Niels Ryberg Finsen", "尼尔斯·吕贝格·芬森", "Denmark")]),
    1904: ("in recognition of his work on the physiology of digestion, through which knowledge on vital aspects of the subject has been transformed and enlarged",
           "表彰他在消化生理学方面的工作，使该领域的重要知识得到转变与扩充",
           [("Ivan Pavlov", "伊万·巴甫洛夫", "Russia")]),
    1905: ("for his investigations and discoveries in relation to tuberculosis",
           "表彰他在结核病方面的研究与发现",
           [("Robert Koch", "罗伯特·科赫", "Germany")]),
    1906: ("in recognition of their work on the structure of the nervous system",
           "表彰他们在神经系统结构方面的工作",
           [("Camillo Golgi", "卡米洛·高尔基", "Italy"),
            ("Santiago Ramón y Cajal", "圣地亚哥·拉蒙·卡哈尔", "Spain")]),
    1907: ("in recognition of his work on the role played by protozoa in causing diseases",
           "表彰他关于原生动物在致病中所起作用的工作",
           [("Charles Louis Alphonse Laveran", "夏尔·路易·阿方斯·拉韦朗", "France")]),
    1908: ("in recognition of their work on immunity",
           "表彰他们在免疫方面的工作",
           [("Élie Metchnikoff", "埃黎耶·梅契尼科夫", "Russia"),
            ("Paul Ehrlich", "保罗·埃尔利希", "Germany")]),
    1909: ("for his work on the physiology, pathology and surgery of the thyroid gland",
           "表彰他在甲状腺的生理学、病理学与外科学方面的工作",
           [("Emil Theodor Kocher", "埃米尔·特奥多尔·科赫尔", "Switzerland")]),
    1910: ("in recognition of the contributions to our knowledge of cell chemistry made through his work on proteins, including the nucleic substances",
           "表彰他通过对蛋白质（包括核酸物质）的研究，对细胞化学知识的贡献",
           [("Albrecht Kossel", "阿尔布雷希特·科塞尔", "Germany")]),
    1911: ("for his work on the dioptrics of the eye",
           "表彰他在眼的屈光学方面的工作",
           [("Allvar Gullstrand", "阿尔瓦·古尔斯特兰德", "Sweden")]),
    1912: ("for his work on vascular suture and the transplantation of blood vessels and organs",
           "表彰他在血管缝合以及血管与器官移植方面的工作",
           [("Alexis Carrel", "亚历克西·卡雷尔", "France")]),
    1913: ("for his work on anaphylaxis",
           "表彰他在过敏反应方面的工作",
           [("Charles Richet", "夏尔·里歇", "France")]),
    1914: ("for his work on the physiology and pathology of the vestibular apparatus",
           "表彰他在前庭器官的生理学与病理学方面的工作",
           [("Robert Bárány", "罗伯特·巴拉尼", "Austria-Hungary")]),
    1919: ("for his discoveries relating to immunity",
           "表彰他与免疫相关的发现",
           [("Jules Bordet", "朱尔斯·博尔代", "Belgium")]),
    1920: ("for his discovery of the capillary motor regulating mechanism",
           "表彰他发现毛细血管运动调节机制",
           [("August Krogh", "奥古斯特·克罗格", "Denmark")]),
    1922: ("for his discovery relating to the production of heat in the muscle || for his discovery of the fixed relationship between the consumption of oxygen and the metabolism of lactic acid in the muscle",
           "表彰他关于肌肉产热的发现 || 表彰他发现肌肉中氧耗量与乳酸代谢之间的固定关系",
           [("Archibald Hill", "阿奇博尔德·希尔", UK),
            ("Otto Fritz Meyerhof", "奥托·弗里茨·迈尔霍夫", "Germany")]),
    1923: ("for the discovery of insulin",
           "表彰他们发现胰岛素",
           [("Frederick Banting", "弗雷德里克·班廷", "Canada"),
            ("John Macleod (physiologist)", "约翰·麦克劳德", "Canada")]),
    1924: ("for the discovery of the mechanism of the electrocardiogram",
           "表彰他发现心电图机制",
           [("Willem Einthoven", "威廉·埃因托芬", "Netherlands")]),
    1926: ("for his discovery of the Spiroptera carcinoma",
           "表彰他发现螺旋体癌（Spiroptera carcinoma）",
           [("Johannes Fibiger", "约翰内斯·菲比格", "Denmark")]),
    1927: ("for his discovery of the therapeutic value of malaria inoculation in the treatment of dementia paralytica",
           "表彰他发现疟疾接种在治疗麻痹性痴呆中的疗效",
           [("Julius Wagner-Jauregg", "朱利叶斯·瓦格纳-尧雷格", "Austria")]),
    1928: ("for his work on typhus",
           "表彰他在斑疹伤寒方面的工作",
           [("Charles Nicolle", "夏尔·尼科尔", "France")]),
    1929: ("for his discovery of the antineuritic vitamin || for his discovery of the growth-stimulating vitamins",
           "表彰他发现抗神经炎维生素 || 表彰他发现促进生长的维生素",
           [("Christiaan Eijkman", "克里斯蒂安·艾克曼", "Netherlands"),
            ("Frederick Gowland Hopkins", "弗雷德里克·高兰·霍普金斯", UK)]),
    1930: ("for his discovery of human blood groups",
           "表彰他发现人类血型",
           [("Karl Landsteiner", "卡尔·兰德施泰纳", "Austria")]),
    1931: ("for his discovery of the nature and mode of action of the respiratory enzyme",
           "表彰他发现呼吸酶的性质与作用方式",
           [("Otto Heinrich Warburg", "奥托·海因里希·瓦尔堡", "Germany")]),
    1932: ("for their discoveries regarding the functions of neurons",
           "表彰他们关于神经元功能的发现",
           [("Charles Scott Sherrington", "查尔斯·斯科特·谢灵顿", UK),
            ("Edgar Adrian", "埃德加·阿德里安", UK)]),
    1933: ("for his discoveries concerning the role played by the chromosome in heredity",
           "表彰他关于染色体在遗传中所起作用的发现",
           [("Thomas Hunt Morgan", "托马斯·亨特·摩尔根", US)]),
    1934: ("for their discoveries concerning liver therapy in cases of anaemia",
           "表彰他们关于贫血的肝脏疗法的发现",
           [("George Whipple", "乔治·惠普尔", US),
            ("George Minot", "乔治·迈诺特", US),
            ("William P. Murphy", "威廉·帕里·墨菲", US)]),
    1935: ("for his discovery of the organizer effect in embryonic development",
           "表彰他发现胚胎发育中的组织者效应",
           [("Hans Spemann", "汉斯·施佩曼", "Germany")]),
    1936: ("for their discoveries relating to chemical transmission of nerve impulses",
           "表彰他们关于神经冲动化学传递的发现",
           [("Henry Hallett Dale", "亨利·哈利特·戴尔", UK),
            ("Otto Loewi", "奥托·勒维", "Austria")]),
    1937: ("for his discoveries in connection with the biological combustion processes, with special reference to vitamin C and the catalysis of fumaric acid",
           "表彰他与生物氧化燃烧过程有关的发现，特别是关于维生素 C 和延胡索酸催化的研究",
           [("Albert Szent-Györgyi", "阿尔伯特·圣捷尔吉", "Hungary")]),
    1938: ("for the discovery of the role played by the sinus and aortic mechanisms in the regulation of respiration",
           "表彰他发现窦房与主动脉机制在呼吸调节中的作用",
           [("Corneille Heymans", "科内耶·海曼斯", "Belgium")]),
    1939: ("for the discovery of the antibacterial effects of prontosil",
           "表彰他发现百浪多息（prontosil）的抗菌作用",
           [("Gerhard Domagk", "格哈德·多马克", "Germany")]),
    1943: ("for his discovery of vitamin K",
           "表彰他发现维生素 K",
           [("Henrik Dam", "亨里克·达姆", "Denmark"),
            ("Edward Adelbert Doisy", "爱德华·阿德尔伯特·多伊西", US)]),
    1944: ("for their discoveries relating to the highly differentiated functions of single nerve fibres",
           "表彰他们关于单条神经纤维高度分化功能的发现",
           [("Joseph Erlanger", "约瑟夫·厄尔兰格", US),
            ("Herbert Spencer Gasser", "赫伯特·斯宾塞·加瑟", US)]),
    1945: ("for the discovery of penicillin and its curative effect in various infectious diseases",
           "表彰他们发现青霉素及其对多种传染性疾病的疗效",
           [("Alexander Fleming", "亚历山大·弗莱明", UK),
            ("Ernst Chain", "恩斯特·伯利斯·钱恩", UK),
            ("Howard Florey", "霍华德·沃尔特·弗洛里", "Australia")]),
    1946: ("for the discovery of the production of mutations by means of X-ray irradiation",
           "表彰他发现 X 射线辐照可诱发突变",
           [("Hermann Joseph Muller", "赫尔曼·约瑟夫·马勒", US)]),
    1947: ("for their discovery of the course of the catalytic conversion of glycogen || for his discovery of the part played by the hormone of the anterior pituitary lobe in the metabolism of sugar",
           "表彰他们发现糖原催化转化的过程 || 表彰他发现脑垂体前叶激素在糖代谢中所起的作用",
           [("Carl Ferdinand Cori", "卡尔·费迪南德·科里", US),
            ("Gerty Cori", "格蒂·特蕾莎·科里", US),
            ("Bernardo Houssay", "贝尔纳多·奥赛", "Argentina")]),
    1948: ("for his discovery of the high efficiency of DDT as a contact poison against several arthropods",
           "表彰他发现 DDT 作为接触性毒剂对多种节肢动物的高效杀灭作用",
           [("Paul Hermann Müller", "保罗·赫尔曼·米勒", "Switzerland")]),
    1949: ("for his discovery of the functional organization of the interbrain as a coordinator of the activities of the internal organs || for his discovery of the therapeutic value of leucotomy in certain psychoses",
           "表彰他发现间脑的功能性组织及其对内脏活动的协调作用 || 表彰他发现脑白质切断术对某些精神疾病的治疗价值",
           [("Walter Rudolf Hess", "瓦尔特·鲁道夫·赫斯", "Switzerland"),
            ("António Egas Moniz", "安东尼奥·埃加斯·莫尼斯", "Portugal")]),
    1950: ("for their discoveries relating to the hormones of the adrenal cortex, their structure and biological effects",
           "表彰他们关于肾上腺皮质激素及其结构和生物学效应的发现",
           [("Philip Showalter Hench", "菲利普·肖瓦尔特·亨奇", US),
            ("Edward Calvin Kendall", "爱德华·卡尔文·肯德尔", US),
            ("Tadeus Reichstein", "塔德乌什·赖希施泰因", "Switzerland")]),
    1951: ("for his discoveries concerning yellow fever and how to combat it",
           "表彰他关于黄热病及其防治的发现",
           [("Max Theiler", "马克斯·泰累尔", "South Africa")]),
    1952: ("for his discovery of streptomycin, the first antibiotic effective against tuberculosis",
           "表彰他发现链霉素——第一种对结核病有效的抗生素",
           [("Selman Waksman", "塞尔曼·亚伯拉罕·瓦克斯曼", US)]),
    1953: ("for his discovery of the citric acid cycle || for his discovery of co-enzyme A and its importance for intermediary metabolism",
           "表彰他发现柠檬酸循环 || 表彰他发现辅酶 A 及其对中间代谢的重要性",
           [("Hans Adolf Krebs", "汉斯·阿道夫·克雷布斯", UK),
            ("Fritz Albert Lipmann", "弗里茨·阿尔伯特·李普曼", US)]),
    1954: ("for their discovery of the ability of poliomyelitis viruses to grow in cultures of various types of tissue",
           "表彰他们发现脊髓灰质炎病毒能够在多种类型的组织培养中生长",
           [("John Franklin Enders", "约翰·富兰克林·恩德斯", US),
            ("Frederick Chapman Robbins", "弗雷德里克·查普曼·罗宾斯", US),
            ("Thomas Huckle Weller", "托马斯·哈克尔·韦勒", US)]),
    1955: ("for his discoveries concerning the nature and mode of action of oxidation enzymes",
           "表彰他关于氧化酶的性质和作用方式的发现",
           [("Hugo Theorell", "胡戈·特奥雷尔", "Sweden")]),
    1956: ("for their discoveries concerning heart catheterization and pathological changes in the circulatory system",
           "表彰他们关于心导管术和循环系统病理变化的发现",
           [("André Frédéric Cournand", "安德烈·弗雷德里克·库尔南", US),
            ("Werner Forssmann", "维尔纳·福斯曼", "Germany"),
            ("Dickinson W. Richards", "迪金森·伍德拉夫·理查兹", US)]),
    1957: ("for his discoveries relating to synthetic compounds that inhibit the action of certain body substances, and especially their action on the vascular system and the skeletal muscles",
           "表彰他发现能抑制某些体内物质作用的合成化合物，尤其是它们对血管系统和骨骼肌的作用",
           [("Daniel Bovet", "达尼埃尔·博韦", "Switzerland")]),
    1958: ("for their discovery that genes act by regulating definite chemical events || for his discoveries concerning genetic recombination and the organization of the genetic material of bacteria",
           "表彰他们发现基因通过调节特定的化学过程而起作用 || 表彰他关于细菌遗传重组及细菌遗传物质组织的发现",
           [("George Wells Beadle", "乔治·韦尔斯·比德尔", US),
            ("Edward Lawrie Tatum", "爱德华·劳里·塔特姆", US),
            ("Joshua Lederberg", "乔舒亚·莱德伯格", US)]),
    1959: ("for their discovery of the mechanisms in the biological synthesis of ribonucleic acid and deoxyribonucleic acid",
           "表彰他们发现核糖核酸和脱氧核糖核酸生物合成的机制",
           [("Arthur Kornberg", "阿瑟·科恩伯格", US),
            ("Severo Ochoa", "塞韦罗·奥乔亚", US)]),
    1960: ("for discovery of acquired immunological tolerance",
           "表彰发现获得性免疫耐受",
           [("Frank Macfarlane Burnet", "弗兰克·麦克法兰·伯内特", "Australia"),
            ("Peter Medawar", "彼得·布赖恩·梅达沃", UK)]),
    1961: ("for his discoveries of the physical mechanism of stimulation within the cochlea",
           "表彰他发现耳蜗内刺激的物理机制",
           [("Georg von Békésy", "格奥尔格·冯·贝凯希", US)]),
    1962: ("for their discoveries concerning the molecular structure of nucleic acids and its significance for information transfer in living material",
           "表彰他们关于核酸分子结构及其对生物体内信息传递意义的发现",
           [("Francis Crick", "弗朗西斯·克里克", UK),
            ("James Watson", "詹姆斯·杜威·沃森", US),
            ("Maurice Wilkins", "莫里斯·休·弗雷德里克·威尔金斯", UK)]),
    1963: ("for their discoveries concerning the ionic mechanisms involved in excitation and inhibition in the peripheral and central portions of the nerve cell membrane",
           "表彰他们关于神经细胞膜外周与中枢部分兴奋和抑制的离子机制的发现",
           [("John Eccles (neurophysiologist)", "约翰·卡鲁·埃克尔斯", "Australia"),
            ("Alan Lloyd Hodgkin", "艾伦·劳埃德·霍奇金", UK),
            ("Andrew Huxley", "安德鲁·菲尔丁·赫胥黎", UK)]),
    1964: ("for their discoveries concerning the mechanism and regulation of the cholesterol and fatty acid metabolism",
           "表彰他们关于胆固醇和脂肪酸代谢的机制与调节的发现",
           [("Konrad Emil Bloch", "康拉德·布洛赫", US),
            ("Feodor Felix Konrad Lynen", "费奥多尔·吕嫩", "Germany")]),
    1965: ("for their discoveries concerning genetic control of enzyme and virus synthesis",
           "表彰他们关于酶与病毒合成的遗传控制的发现",
           [("François Jacob", "弗朗索瓦·雅各布", "France"),
            ("André Michel Lwoff", "安德烈·利沃夫", "France"),
            ("Jacques Monod", "雅克·莫诺", "France")]),
    1966: ("for his discovery of tumour-inducing viruses || for his discoveries concerning hormonal treatment of prostatic cancer",
           "表彰他发现致肿瘤病毒 || 表彰他关于前列腺癌激素疗法的发现",
           [("Francis Peyton Rous", "佩顿·劳斯", US),
            ("Charles Brenton Huggins", "查尔斯·布伦顿·哈金斯", US)]),
    1967: ("for their discoveries concerning the primary physiological and chemical visual processes in the eye",
           "表彰他们关于眼中初级生理与化学视觉过程的发现",
           [("Ragnar Granit", "拉格纳·格拉尼特", "Finland"),
            ("Haldan Keffer Hartline", "霍尔登·凯弗·哈特兰", US),
            ("George Wald", "乔治·沃尔德", US)]),
    1968: ("for their interpretation of the genetic code and its function in protein synthesis",
           "表彰他们解读遗传密码及其在蛋白质合成中功能的发现",
           [("Robert W. Holley", "罗伯特·威廉·霍利", US),
            ("Har Gobind Khorana", "哈尔·戈宾·霍拉纳", US),
            ("Marshall Warren Nirenberg", "马歇尔·沃伦·尼伦伯格", US)]),
    1969: ("for their discoveries concerning the replication mechanism and the genetic structure of viruses",
           "表彰他们关于病毒复制机制和病毒遗传结构的发现",
           [("Max Delbrück", "马克斯·德尔布吕克", US),
            ("Alfred Hershey", "阿尔弗雷德·赫尔希", US),
            ("Salvador Luria", "萨尔瓦多·卢里亚", US)]),
    1970: ("for their discoveries concerning the humoral transmitters in the nerve terminals and the mechanism for their storage, release and inactivation",
           "表彰他们关于神经末梢体液递质及其贮存、释放和失活机制的发现",
           [("Julius Axelrod", "朱利叶斯·阿克塞尔罗德", US),
            ("Ulf von Euler", "乌尔夫·冯·奥伊勒", "Sweden"),
            ("Bernard Katz", "伯纳德·卡茨", UK)]),
    1971: ("for his discoveries concerning the mechanisms of the action of hormones",
           "表彰他关于激素作用机制的发现",
           [("Earl Wilbur Sutherland Jr.", "厄尔·萨瑟兰", US)]),
    1972: ("for their discoveries concerning the chemical structure of antibodies",
           "表彰他们关于抗体化学结构的发现",
           [("Gerald Edelman", "杰拉尔德·埃德尔曼", US),
            ("Rodney Robert Porter", "罗德尼·罗伯特·波特", UK)]),
    1973: ("for their discoveries concerning organization and elicitation of individual and social behaviour patterns",
           "表彰他们关于个体与社会行为模式的组织和引发的发现",
           [("Karl von Frisch", "卡尔·冯·弗里施", "Austria"),
            ("Konrad Lorenz", "康拉德·洛伦茨", "Austria"),
            ("Nikolaas Tinbergen", "尼古拉斯·廷贝亨", UK)]),
    1974: ("for their discoveries concerning the structural and functional organization of the cell",
           "表彰他们关于细胞的结构与功能组织的发现",
           [("Albert Claude", "阿尔伯特·克劳德", "Belgium"),
            ("Christian de Duve", "克里斯蒂安·德·迪夫", "Belgium"),
            ("George Emil Palade", "乔治·埃米尔·帕拉德", US)]),
    1975: ("for their discoveries concerning the interaction between tumour viruses and the genetic material of the cell",
           "表彰他们关于肿瘤病毒与细胞遗传物质之间相互作用的发现",
           [("David Baltimore", "戴维·巴尔的摩", US),
            ("Renato Dulbecco", "雷纳托·杜尔贝科", US),
            ("Howard Martin Temin", "霍华德·马丁·特明", US)]),
    1976: ("for their discoveries concerning new mechanisms for the origin and dissemination of infectious diseases",
           "表彰他们关于传染病起源与传播新机制的发现",
           [("Baruch Samuel Blumberg", "巴鲁克·萨缪尔·布伦伯格", US),
            ("Daniel Carleton Gajdusek", "丹尼尔·卡尔顿·盖杜谢克", US)]),
    1977: ("for their discoveries concerning the peptide hormone production of the brain || for the development of radioimmunoassays of peptide hormones",
           "表彰他们关于脑肽类激素生成的发现 || 表彰她开发肽类激素的放射免疫分析法",
           [("Roger Guillemin", "罗歇·夏尔·吉耶曼", US),
            ("Andrew Schally", "安德鲁·沙利", US),
            ("Rosalyn Sussman Yalow", "罗莎琳·雅洛", US)]),
    1978: ("for the discovery of restriction enzymes and their application to problems of molecular genetics",
           "表彰他们发现限制性内切酶及其在分子遗传学问题上的应用",
           [("Werner Arber", "维尔纳·阿尔伯", "Switzerland"),
            ("Daniel Nathans", "丹尼尔·纳森斯", US),
            ("Hamilton O. Smith", "汉密尔顿·奥内尔·史密斯", US)]),
    1979: ("for the development of computer assisted tomography",
           "表彰计算机辅助断层成像（CT）的研制",
           [("Allan McLeod Cormack", "艾伦·麦克劳德·科马克", US),
            ("Godfrey Hounsfield", "戈弗雷·纽博尔德·豪斯菲尔德", UK)]),
    1980: ("for their discoveries concerning genetically determined structures on the cell surface that regulate immunological reactions",
           "表彰他们关于细胞表面由遗传决定、调节免疫反应的结构的发现",
           [("Baruj Benacerraf", "巴鲁赫·贝纳塞拉夫", US),
            ("Jean Dausset", "让·多塞", "France"),
            ("George D. Snell", "乔治·戴维斯·斯内尔", US)]),
    1981: ("for his discoveries concerning the functional specialization of the cerebral hemispheres || for their discoveries concerning information processing in the visual system",
           "表彰他关于大脑两半球功能特化的发现 || 表彰他们关于视觉系统中信息加工的发现",
           [("Roger Wolcott Sperry", "罗杰·沃尔科特·斯佩里", US),
            ("David H. Hubel", "戴维·亨特·休伯尔", US),
            ("Torsten Wiesel", "托斯滕·尼尔斯·维泽尔", US)]),
    1982: ("for their discoveries concerning prostaglandins and related biologically active substances",
           "表彰他们关于前列腺素及相关生物活性物质的发现",
           [("Sune Bergström", "苏内·贝里斯特伦", "Sweden"),
            ("Bengt I. Samuelsson", "本特·英格马·萨穆埃尔松", "Sweden"),
            ("John Vane", "约翰·罗伯特·文", UK)]),
    1983: ("for her discovery of mobile genetic elements",
           "表彰她发现可移动的遗传元件",
           [("Barbara McClintock", "芭芭拉·麦克林托克", US)]),
    1984: ("for theories concerning the specificity in development and control of the immune system and the discovery of the principle for production of monoclonal antibodies",
           "表彰他们关于免疫系统发育和调控特异性的理论，以及发现单克隆抗体产生的原理",
           [("Niels Kaj Jerne", "尼尔斯·凯·耶恩", "Denmark"),
            ("Georges J. F. Köhler", "乔治·让·弗朗茨·克勒", "Germany"),
            ("César Milstein", "塞萨尔·米尔斯坦", "Argentina")]),
    1985: ("for their discoveries concerning the regulation of cholesterol metabolism",
           "表彰他们关于胆固醇代谢调节的发现",
           [("Michael Stuart Brown", "迈克尔·斯图尔特·布朗", US),
            ("Joseph L. Goldstein", "约瑟夫·伦纳德·戈尔茨坦", US)]),
    1986: ("for their discoveries of growth factors",
           "表彰他们发现生长因子",
           [("Stanley Cohen (biochemist)", "斯坦利·科恩", US),
            ("Rita Levi-Montalcini", "丽塔·列维-蒙塔尔奇尼", "Italy")]),
    1987: ("for his discovery of the genetic principle for generation of antibody diversity",
           "表彰他发现抗体多样性产生的遗传学原理",
           [("Susumu Tonegawa", "利根川进", "Japan")]),
    1988: ("for their discoveries of important principles for drug treatment",
           "表彰他们发现药物治疗的重要原理",
           [("James Black (pharmacologist)", "詹姆斯·怀特·布莱克", UK),
            ("Gertrude B. Elion", "格特鲁德·贝勒·埃利恩", US),
            ("George H. Hitchings", "乔治·赫伯特·希钦斯", US)]),
    1989: ("for their discovery of the cellular origin of retroviral oncogenes",
           "表彰他们发现逆转录病毒癌基因的细胞起源",
           [("J. Michael Bishop", "约翰·迈克尔·毕晓普", US),
            ("Harold E. Varmus", "哈罗德·埃利奥特·瓦慕斯", US)]),
    1990: ("for their discoveries concerning organ and cell transplantation in the treatment of human disease",
           "表彰他们关于器官和细胞移植治疗人类疾病的发现",
           [("Joseph Murray", "约瑟夫·爱德华·默里", US),
            ("E. Donnall Thomas", "唐纳尔·托马斯", US)]),
    1991: ("for their discoveries concerning the function of single ion channels in cells",
           "表彰他们关于细胞内单离子通道功能的发现",
           [("Erwin Neher", "埃尔温·内尔", "Germany"),
            ("Bert Sakmann", "贝特·萨克曼", "Germany")]),
    1992: ("for their discoveries concerning reversible protein phosphorylation as a biological regulatory mechanism",
           "表彰他们发现可逆蛋白质磷酸化作为一种生物调节机制",
           [("Edmond H. Fischer", "埃德蒙·亨利·费希尔", US),
            ("Edwin G. Krebs", "埃德温·格哈德·克雷布斯", US)]),
    1993: ("for their discoveries of split genes",
           "表彰他们发现断裂基因",
           [("Richard J. Roberts", "理查德·约翰·罗伯茨", UK),
            ("Phillip Allen Sharp", "菲利普·艾伦·夏普", US)]),
    1994: ("for their discovery of G-proteins and the role of these proteins in signal transduction in cells",
           "表彰他们发现 G 蛋白及这些蛋白在细胞信号转导中的作用",
           [("Alfred G. Gilman", "阿尔弗雷德·古德曼·吉尔曼", US),
            ("Martin Rodbell", "马丁·罗德贝尔", US)]),
    1995: ("for their discoveries concerning the genetic control of early embryonic development",
           "表彰他们关于早期胚胎发育遗传控制的发现",
           [("Edward B. Lewis", "爱德华·布赖恩特·刘易斯", US),
            ("Christiane Nüsslein-Volhard", "克里斯蒂安娜·尼斯莱因-福尔哈德", "Germany"),
            ("Eric F. Wieschaus", "埃里克·弗朗西斯·威绍斯", US)]),
    1996: ("for their discoveries concerning the specificity of the cell mediated immune defence",
           "表彰他们关于细胞介导免疫防御特异性的发现",
           [("Peter C. Doherty", "彼得·查尔斯·多尔蒂", "Australia"),
            ("Rolf M. Zinkernagel", "罗尔夫·马丁·青克纳格尔", "Switzerland")]),
    1997: ("for his discovery of Prions - a new biological principle of infection",
           "表彰他发现朊病毒——一种新的感染生物学原理",
           [("Stanley B. Prusiner", "斯坦利·本·普鲁西纳", US)]),
    1998: ("for their discoveries concerning nitric oxide as a signalling molecule in the cardiovascular system",
           "表彰他们关于一氧化氮作为心血管系统信号分子的发现",
           [("Robert F. Furchgott", "罗伯特·弗朗西斯·弗奇戈特", US),
            ("Louis Ignarro", "路易斯·伊格纳罗", US),
            ("Ferid Murad", "费里德·穆拉德", US)]),
    1999: ("for the discovery that proteins have intrinsic signals that govern their transport and localization in the cell",
           "表彰他发现蛋白质具有控制其在细胞内运输和定位的内在信号",
           [("Günter Blobel", "京特·布洛贝尔", US)]),
    2000: ("for their discoveries concerning signal transduction in the nervous system",
           "表彰他们关于神经系统中信号传导的发现",
           [("Arvid Carlsson", "阿维德·卡尔松", "Sweden"),
            ("Paul Greengard", "保罗·格林加德", US),
            ("Eric Kandel", "埃里克·坎德尔", US)]),
    2001: ("for their discoveries of key regulators of the cell cycle",
           "表彰他们发现细胞周期的关键调节因子",
           [("Leland H. Hartwell", "利兰·哈特韦尔", US),
            ("Tim Hunt", "蒂姆·亨特", UK),
            ("Paul Nurse", "保罗·马斯顿·纳斯", UK)]),
    2002: ("for their discoveries concerning 'genetic regulation of organ development and programmed cell death'",
           "表彰他们关于「器官发育和程序性细胞死亡的遗传调控」的发现",
           [("Sydney Brenner", "悉尼·布伦纳", UK),
            ("H. Robert Horvitz", "霍华德·罗伯特·霍维茨", US),
            ("John Sulston", "约翰·爱德华·苏尔斯顿", UK)]),
    2003: ("for their discoveries concerning magnetic resonance imaging",
           "表彰他们关于磁共振成像的发现",
           [("Paul Lauterbur", "保罗·劳特伯", US),
            ("Peter Mansfield", "彼得·曼斯菲尔德", UK)]),
    2004: ("for their discoveries of odorant receptors and the organization of the olfactory system",
           "表彰他们发现气味受体并阐明嗅觉系统的组织结构",
           [("Richard Axel", "理查德·阿克塞尔", US),
            ("Linda B. Buck", "琳达·巴克", US)]),
    2005: ("for their discovery of the bacterium Helicobacter pylori and its role in gastritis and peptic ulcer disease",
           "表彰他们发现幽门螺杆菌及其在胃炎和消化性溃疡病中的作用",
           [("Barry Marshall", "巴里·马歇尔", "Australia"),
            ("J. Robin Warren", "罗宾·沃伦", "Australia")]),
    2006: ("for their discovery of RNA interference - gene silencing by double-stranded RNA",
           "表彰他们发现 RNA 干扰——双链 RNA 引发的基因沉默",
           [("Andrew Fire", "安德鲁·法尔", US),
            ("Craig Mello", "克雷格·梅洛", US)]),
    2007: ("for their discoveries of principles for introducing specific gene modifications in mice by the use of embryonic stem cells",
           "表彰他们发现利用胚胎干细胞在小鼠中引入特定基因修饰的原理",
           [("Mario Capecchi", "马里奥·伦佐·卡佩基", US),
            ("Martin Evans", "马丁·约翰·埃文斯", UK),
            ("Oliver Smithies", "奥利弗·史密西斯", US)]),
    2008: ("for his discovery of human papilloma viruses causing cervical cancer || for their discovery of human immunodeficiency virus",
           "表彰他发现导致宫颈癌的人乳头瘤病毒 || 表彰他们发现人类免疫缺陷病毒",
           [("Harald zur Hausen", "哈拉尔德·楚尔·豪森", "Germany"),
            ("Françoise Barré-Sinoussi", "弗朗索瓦丝·巴尔-西诺西", "France"),
            ("Luc Montagnier", "吕克·蒙塔尼耶", "France")]),
    2009: ("for the discovery of how chromosomes are protected by telomeres and the enzyme telomerase",
           "表彰他们发现端粒和端粒酶如何保护染色体",
           [("Elizabeth Blackburn", "伊丽莎白·海伦·布莱克本", US),
            ("Carol W. Greider", "卡罗尔·格雷德", US),
            ("Jack W. Szostak", "杰克·绍斯塔克", US)]),
    2010: ("for the development of in vitro fertilization",
           "表彰体外受精技术的研制",
           [("Robert G. Edwards", "罗伯特·杰弗里·爱德华兹", UK)]),
    2011: ("for their discoveries concerning the activation of innate immunity || for his discovery of the dendritic cell and its role in adaptive immunity",
           "表彰他们关于先天免疫激活的发现 || 表彰他发现树突状细胞及其在获得性免疫中的作用",
           [("Bruce Beutler", "布鲁斯·博伊特勒", US),
            ("Jules A. Hoffmann", "朱尔斯·霍夫曼", "France"),
            ("Ralph M. Steinman", "拉尔夫·斯坦曼", "Canada")]),
    2012: ("for the discovery that mature cells can be reprogrammed to become pluripotent",
           "表彰成熟细胞可被重编程为多能细胞的发现",
           [("John Gurdon", "约翰·格登", UK),
            ("Shinya Yamanaka", "山中伸弥", "Japan")]),
    2013: ("for their discoveries of machinery regulating vesicle traffic, a major transport system in our cells",
           "表彰他们发现调节囊泡运输的机制——细胞内主要的运输系统",
           [("James E. Rothman", "詹姆斯·罗斯曼", US),
            ("Randy W. Schekman", "兰迪·韦恩·谢克曼", US),
            ("Thomas C. Südhof", "托马斯·聚德霍夫", US)]),
    2014: ("for their discoveries of cells that constitute a positioning system in the brain",
           "表彰他们发现构成大脑定位系统的细胞",
           [("John O'Keefe (neuroscientist)", "约翰·奥基夫", US),
            ("May-Britt Moser", "梅-布里特·莫泽", "Norway"),
            ("Edvard I. Moser", "爱德华·莫泽", "Norway")]),
    2015: ("for their discoveries concerning a novel therapy against infections caused by roundworm parasites || for her discoveries concerning a novel therapy against Malaria",
           "表彰他们关于对抗线虫寄生感染的新型疗法的发现 || 表彰她关于疟疾新型疗法的发现",
           [("William C. Campbell (scientist)", "威廉·坎贝尔", "Ireland"),
            ("Satoshi Ōmura", "大村智", "Japan"),
            ("Tu Youyou", "屠呦呦", "China")]),
    2016: ("for his discoveries of mechanisms for autophagy",
           "表彰他发现细胞自噬机制",
           [("Yoshinori Ohsumi", "大隅良典", "Japan")]),
    2017: ("for their discoveries of molecular mechanisms controlling the circadian rhythm",
           "表彰他们发现控制昼夜节律的分子机制",
           [("Jeffrey C. Hall", "杰弗里·霍尔", US),
            ("Michael Rosbash", "迈克尔·罗斯巴什", US),
            ("Michael W. Young", "迈克尔·沃伦·扬", US)]),
    2018: ("for their discovery of cancer therapy by inhibition of negative immune regulation",
           "表彰他们通过抑制负向免疫调节发现癌症疗法",
           [("James P. Allison", "詹姆斯·艾利森", US),
            ("Tasuku Honjo", "本庶佑", "Japan")]),
    2019: ("for their discoveries of how cells sense and adapt to oxygen availability",
           "表彰他们发现细胞如何感知并适应氧供应",
           [("William Kaelin Jr.", "威廉·凯林", US),
            ("Peter J. Ratcliffe", "彼得·拉特克利夫", UK),
            ("Gregg L. Semenza", "格雷格·塞门扎", US)]),
    2020: ("for the discovery of Hepatitis C virus",
           "表彰发现丙型肝炎病毒",
           [("Harvey J. Alter", "哈维·詹姆斯·奥尔特", US),
            ("Michael Houghton (virologist)", "迈克尔·霍顿", UK),
            ("Charles M. Rice", "查尔斯·赖斯", US)]),
    2021: ("for the discovery of receptors for temperature and touch",
           "表彰他们发现温度和触觉受体",
           [("David Julius", "戴维·朱利叶斯", US),
            ("Ardem Patapoutian", "阿德姆·帕塔普蒂安", US)]),
    2022: ("for his discoveries concerning the genomes of extinct hominins and human evolution",
           "表彰他关于已灭绝人类基因组和人类进化的发现",
           [("Svante Pääbo", "斯万特·帕博", "Sweden")]),
    2023: ("for their discoveries concerning nucleoside base modifications that enabled the development of effective mRNA vaccines against COVID-19",
           "表彰他们关于核苷碱基修饰的发现，这些发现使针对 COVID-19 的有效 mRNA 疫苗得以研制",
           [("Katalin Karikó", "卡塔琳·考里科", US),
            ("Drew Weissman", "德鲁·韦斯曼", US)]),
    2024: ("for the discovery of microRNA and its role in post-transcriptional gene regulation",
           "表彰他们发现 microRNA 及其在转录后基因调控中的作用",
           [("Victor Ambros", "维克托·安布罗斯", US),
            ("Gary Ruvkun", "加里·鲁夫昆", US)]),
    2025: ("for their discoveries concerning peripheral immune tolerance",
           "表彰他们关于外周免疫耐受的发现",
           [("Mary E. Brunkow", "玛丽·埃伦·布伦科", US),
            ("Fred Ramsdell", "弗雷德·拉姆斯德尔", US),
            ("Shimon Sakaguchi", "坂口志文", "Japan")]),
}
