#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""批量补充 awards 字典中 name_zh 缺失/为英文的中文名（模式匹配翻译）。
只更新 name_zh=name_en 的条目，幂等（重复运行无害）。"""
import re
from db_mysql import get_conn

# 具体名称翻译（精确匹配）
EXACT = {
    "Wihuri International Prize": "维胡里国际奖",
    "Henrik Steffens Prize": "亨里克·斯特芬斯奖",
    "Cross of Liberty, 2nd Class": "自由十字勋章（二级）",
    "Grand Cross of the Order of the White Rose of Finland": "芬兰白玫瑰勋章大十字勋位",
    "Commander First Class of the Order of the White Rose of Finland": "芬兰白玫瑰勋章一等司令勋位",
    "Commander of the Order of the White Rose of Finland": "芬兰白玫瑰勋章司令勋位",
    "Knight First Class of the Order of the White Rose of Finland": "芬兰白玫瑰勋章一等骑士勋位",
    "Medal of Liberty, 2nd Class": "自由奖章（二级）",
    "Memorial medal of the Winter War": "冬季战争纪念奖章",
    "Memorial medal of the Continuation War": "续战纪念奖章",
    "Grand Officer of the Order of the Star of Romania": "罗马尼亚之星勋章大官佐勋位",
    "Order of the German Eagle": "德国之鹰勋章",
    "USSR State Prize": "苏联国家奖",
    "Order of the Badge of Honour": "荣誉徽章勋章",
    "State Stalin Prize, 1st degree": "斯大林国家奖（一级）",
    "Grand Cross of the National Order of Scientific Merit": "国家科学功绩勋章大十字勋位",
    "Srinivasa Ramanujan Medal": "拉马努金奖章",
    "Padma Bhushan": "莲花赐勋章（Padma Bhushan）",
    "John von Neumann Award": "约翰·冯·诺伊曼奖",
    "W. T. and Idalia Reid Prize": "里德奖（SIAM）",
    "Grand Officer of the National Order of Merit": "国家功绩勋章大官佐勋位",
    "Order of the Rising Sun, Gold and Silver Star": "旭日勋章（金银星章）",
    "Commander First Class of the Order of the Lion of Finland": "芬兰狮子勋章一等司令勋位",
    "Order of the White Eagle": "白鹰勋章",
    "Longuet-Higgins Prize": "朗盖-希金斯奖",
    "Nemmers Prize in Mathematics": "内默斯数学奖",
    "Shaw Prize": "邵逸夫奖",
    "Kyoto Prize in Basic Sciences": "京都奖（基础科学类）",
    "Crafoord Prize in Mathematics": "克拉福德数学奖",
    "Lomonosov Gold Medal": "罗蒙诺索夫金质奖章",
    "Leonhard Euler Gold Medal": "欧拉金质奖章",
    "Sloan Fellowship": "斯隆研究基金",
    "MacArthur Fellowship": "麦克阿瑟奖",
    "Putnam Fellow": "普特南竞赛优胜者",
    "Guggenheim Fellowship": "古根海姆研究基金",
    "Order of the Red Banner of Labour": "劳动红旗勋章",
    "Order of the October Revolution": "十月革命勋章",
    "Order of Lenin": "列宁勋章",
    "Hero of Socialist Labour": "社会主义劳动英雄",
    "Order of the Patriotic War, 1st class": "一级卫国战争勋章",
    "Order of Merit of the Federal Republic of Germany": "联邦德国功绩勋章",
    "Knight Commander's Cross of the Order of Merit of the Federal Republic of Germany": "联邦德国功绩勋章司令十字",
    "Order of Merit": "功绩勋章",
    "Commander of the Legion of Honour": "荣誉军团司令勋位",
    "Officer of the Legion of Honour": "荣誉军团军官勋位",
    "Legion of Honour": "荣誉军团勋章",
    "Knight Bachelor": "下级勋位爵士（Knight Bachelor）",
    "Fellow of the Royal Society": "英国皇家学会会士",
    "Foreign Member of the Royal Society": "英国皇家学会外籍会士",
    "ForMemRS": "英国皇家学会外籍会士",
    "Member of the National Academy of Sciences": "美国国家科学院院士",
    "Fellow of the American Mathematical Society": "美国数学学会会士",
    "Fellow of the American Physical Society": "美国物理学会会士",
    "Fellow of the Institute of Mathematical Statistics": "数理统计学会会士",
    "Fellow of the Econometric Society": "计量经济学会会士",
    "Fellow of the Society for Industrial and Applied Mathematics": "工业与应用数学学会会士",
    "Fellow of the American Academy of Arts and Sciences": "美国艺术与科学院院士",
    "Academician of the Chinese Academy of Sciences": "中国科学院院士",
    "Order of the White Rose of Finland": "芬兰白玫瑰勋章",
    "Order of the Lion of Finland": "芬兰狮子勋章",
    "Royal Order of the Polar Star": "北极星勋章",
    "Gold Medal of the Royal Astronomical Society": "皇家天文学会金质奖章",
    "Bruce Medal": "布鲁斯奖章",
    "Matteucci Medal": "马泰乌奇奖章",
    "Bôcher Memorial Prize": "博赫尔纪念奖",
    "Sylvester Medal": "西尔维斯特奖章",
    "De Morgan Medal": "德摩根奖章",
    "Copley Medal": "科普利奖章",
    "Royal Medal": "皇家奖章",
    "Darwin Medal": "达尔文奖章",
    "Darwin–Wallace Medal": "达尔文-华莱士奖章",
    "Guy Medal in Gold": "盖伊金质奖章",
    "Weldon Memorial Prize": "韦尔登纪念奖",
    "Silliman Memorial Lectures": "西利曼纪念讲座",
    "Croonian Medal and Lecture": "克鲁尼安奖章与讲座",
    "Albert Einstein Award": "阿尔伯特·爱因斯坦奖",
    "Bateson Lecture": "贝特森讲座",
    "Poncelet Prize": "彭赛列奖",
    "Cothenius Medal": "科特尼乌斯奖章",
    "Goethe Medal for Art and Science": "歌德艺术与科学奖章",
    "Bavarian Maximilian Order for Science and Art": "巴伐利亚马克西米利安科学与艺术勋章",
    "Pour le Mérite for Sciences and Arts order": "功勋勋章（科学与艺术）",
    "Pour le Mérite for Sciences and Arts": "功勋勋章（科学与艺术）",
    "Cours Peccot": "佩科课程奖",
    "Prix Francoeur": "弗朗科尔奖",
    "Émile Picard Medal": "埃米尔·皮卡德奖章",
    "Leroy P. Steele Prize": "斯蒂尔奖",
    "Leroy P. Steele Prize for Mathematical Exposition": "斯蒂尔数学阐述奖",
    "Barnard Medal for Meritorious Service to Science": "巴纳德科学功勋奖章",
    "Balzan Prize": "巴尔赞奖",
    "Heineman Prize": "海涅曼数学物理奖",
    "Dannie Heineman Prize for Mathematical Physics": "海涅曼数学物理奖",
    "Harvey Prize": "哈维奖",
    "Kyoto Prize": "京都奖",
    "Kyoto Prize in Basic Sciences": "京都奖（基础科学类）",
    "National Medal of Science": "国家科学奖章",
    "Order of the British Empire": "大英帝国勋章",
    "Officer of the Order of the British Empire": "大英帝国官佐勋章（OBE）",
    "Smith's Prize": "史密斯奖",
    "Ackermann–Teubner Memorial Award": "阿克曼-托伊布纳纪念奖",
    "Gaston-Julia Award": "加斯东·朱利亚奖",
    "Chauvenet Prize": "肖夫内奖",
    "Oswald Veblen Prize in Geometry": "奥斯瓦尔德·维布伦几何奖",
    "Humboldt Prize": "洪堡研究奖",
    "Humboldt Research Fellowship": "洪堡研究基金",
    "William Procter Prize for Scientific Achievement": "威廉·普罗克特科学成就奖",
    "BBVA Foundation Frontiers of Knowledge Award": "BBVA 知识前沿奖",
    "Alfred Noble Prize": "阿尔弗雷德·诺布尔奖",
    "IEEE Morris N. Liebmann Memorial Award": "IEEE 利布曼纪念奖",
    "Stuart Ballantine Medal": "斯图尔特·巴兰坦奖章",
    "IEEE Medal of Honor": "IEEE 荣誉奖章",
    "Harold Pender Award": "哈罗德·彭德奖",
    "John Fritz Medal": "约翰·弗里茨奖章",
    "Claude E. Shannon Award": "克劳德·香农奖",
    "Marconi Prize": "马可尼奖",
    "National Inventors Hall of Fame": "国家发明家名人堂",
    "Frank Nelson Cole Prize in Number Theory": "科尔数论奖",
    "Cole Prize in Number Theory": "科尔数论奖",
    "Cole Prize in Algebra": "科尔代数学奖",
    "Leconte Prize": "勒孔特奖",
    "Bolyai Prize": "波尔约奖",
    "Lobachevsky Prize": "罗巴切夫斯基奖",
    "Lobachevsky Medal": "罗巴切夫斯基奖章",
    "RAS Lobachevsky Prize": "俄罗斯科学院罗巴切夫斯基奖",
    "PL Chebyshev Gold Medal": "契比雪夫金质奖章",
    "P.L. Chebyshev Gold Medal": "契比雪夫金质奖章",
    "Helmholtz Medal": "亥姆霍兹奖章",
    "Stalin Prize": "斯大林奖",
    "Lenin Prize": "列宁奖",
    "Order of Saint Olav": "圣奥拉夫勋章",
    "Knight Grand Officer of the Order of Saint Olav": "圣奥拉夫勋章大官佐勋位",
    "Gunnerus Medal": "贡纳鲁斯奖章",
    "Grand Prix de l'Etat": "国家大奖",
    "Grand prix des sciences mathématiques": "数学科学大奖",
    "Prix de l'Etat": "国家大奖",
    "Prix de la Fondation Peccot": "佩科基金奖",
    "Guy Medal in Silver": "盖伊银质奖章",
    "James Prize": "詹姆斯奖",
    "Senior Berwick Prize": "高级贝里克奖",
    "Berwick Prize": "贝里克奖",
    "Sylvester Medal": "西尔维斯特奖章",
    "Faraday Lectureship": "法拉第讲座奖",
    "Julius Edgar Lilienfeld Prize": "利连菲尔德奖",
    "Order of the Netherlands Lion": "荷兰狮子勋章",
    "Order of Orange-Nassau": "奥兰治-拿骚勋章",
    "Knight of the Order of the Netherlands Lion": "荷兰狮子勋章骑士勋位",
    "Academic Palms": "学术棕榈勋章",
    "Croix de guerre 1939–1945": "1939-1945 战争十字勋章",
    "Croix de guerre": "战争十字勋章",
    "Concours général": "全国会考奖（Concours général）",
    "Goldsmiths' Prize": "金匠公司奖",
    "Stirling Prize": "斯特灵奖",
    "Brasseur Prize": "布拉瑟奖",
    "Chauvenet Prize": "肖夫内奖",
    "Eckert–Mauchly Award": "埃克特-莫奇利奖",
    "Hoeffding Prize": "霍夫丁奖",
    "Mohammed Reza Pahlavi Prize": "巴列维奖",
    "Fejér Prize": "费耶尔奖",
    "Jean Reynaud Prize": "让·雷诺奖",
    "Royal Danish Academy of Sciences and Letters": "丹麦皇家科学院",
    "Grand Prix des Sciences": "科学大奖",
    "Nemmers Prize": "内默斯奖",
    "Steele Prize for Mathematical Exposition": "斯蒂尔数学阐述奖",
    "Shaw Prize in Mathematical Sciences": "邵逸夫数学科学奖",
    "The Shaw Prize in Mathematical Sciences": "邵逸夫数学科学奖",
    "King Faisal International Prize for Science": "费萨尔国王国际科学奖",
    "King Faisal International Prize": "费萨尔国王国际奖",
    "Order of the Star of Romania": "罗马尼亚之星勋章",
    "Order of the Polar Star": "北极星勋章",
    "Sir Ratan Tata Trust": "塔塔信托",
    "Templeton Prize": "邓普顿奖",
    "Prestigious Padma Bhushan": "莲花赐勋章（Padma Bhushan）",
    "Fellow of the Academy of Medical Sciences": "医学科学院会士",
    "Honorary Doctorate from the National Autonomous University of Mexico": "墨西哥国立自治大学荣誉博士",
    "Honorary Fellow of the Learned Society of Wales": "威尔士学会荣誉会士",
    "IET Kelvin Lecture": "IET 开尔文讲座",
    "Gunning Victoria Jubilee Prize": "甘宁维多利亚禧年奖",
    "President's Medal": "会长奖章",
    "Order of Andrés Bello": "安德烈斯·贝略勋章",
    "Feltrinelli Prize": "费尔特里内利奖",
    "Benjamin Franklin Medal": "本杰明·富兰克林奖章",
    "Forder Lectureship": "福德讲座",
    "Fellow of the Australian Academy of Science": "澳大利亚科学院院士",
    "Alan T. Waterman Award": "沃特曼奖",
    "Joseph Doob Prize": "杜布奖",
    "Steele Prize for Seminal Contribution to Research": "斯蒂尔开创性研究贡献奖",
    "Croix de guerre 1914–1918": "1914-1918 战争十字勋章",
    "Knight of the Legion of Honour": "荣誉军团骑士勋位",
    "Iron Cross": "铁十字勋章",
    "Edwin Howard Armstrong Achievement Award": "阿姆斯特朗成就奖",
    "Noble Prize": "诺布尔奖（Alfred Noble Prize）",
    "Dannie Heineman Prize": "海涅曼数学物理奖",
    "Q21660832": "未知奖项（Q21660832）",
    "Leonard Euler Gold Medal": "欧拉金质奖章",
    "State Prize of the Russian Federation": "俄罗斯联邦国家奖",
    "Order \"For Merit to the Fatherland\", 4th class": "祖国功绩勋章（四级）",
    "Honorary doctor of the University of Liège": "列日大学荣誉博士",
    "Knight Grand Cross of the Order of Merit of the Federal Republic of Germany": "联邦德国功绩勋章大十字",
    "Sloan Research Fellowship": "斯隆研究基金",
    "Doctor honoris causa from the University of Paris": "巴黎大学荣誉博士",
    "Order of the Rising Sun": "旭日勋章",
    "Commander of the Order of the British Empire": "大英帝国司令勋位（CBE）",
    "Member of the Order of the British Empire": "大英帝国员佐勋位（MBE）",
    "Officer of the Order of the British Empire": "大英帝国官佐勋章（OBE）",
    "Companion of Honour": "荣誉勋位",
    "Foreign Member of the Russian Academy of Sciences": "俄罗斯科学院外籍院士",
    "Full Member of the Russian Academy of Sciences": "俄罗斯科学院院士",
    "Corresponding Member of the USSR Academy of Sciences": "苏联科学院通讯院士",
    "Full Member of the USSR Academy of Sciences": "苏联科学院院士",
    "Foreign Associate of the National Academy of Sciences": "美国国家科学院外籍院士",
    "Honorary Member of the London Mathematical Society": "伦敦数学学会荣誉会员",
    "Pitman Medal": "皮特曼奖章",
    "Abraham de Moivre Medal": "棣莫弗奖章",
    "Gauss Prize": "高斯奖",
    "Chern Medal": "陈省身奖章",
    "Chern Medal Award": "陈省身奖章",
    "MacArthur Fellows Program": "麦克阿瑟奖",
    "Longuet-Higgins Prize": "朗盖-希金斯奖",
    "Steele Prize for Lifetime Achievement": "斯蒂尔终身成就奖",
    "Stoll Prize": "斯托尔奖",
    "Morningside Medal": "晨兴奖章",
    "Morningside Gold Medal": "晨兴金奖章",
    "Clay Research Award": "克莱研究奖",
    "Breakthrough Prize in Mathematics": "数学突破奖",
    "Schock Prize": "肖克奖",
    "Körber European Science Prize": "科尔伯欧洲科学奖",
    "Prize of the Foundation Rolf Schock": "肖克奖",
    "Hardy Prize": "哈代奖",
    "Adams Prize": "亚当斯奖",
    "Sylvester Prize": "西尔维斯特奖",
    "Whitehead Prize": "怀特海奖",
    "Senior Whitehead Prize": "高级怀特海奖",
    "De Morgan Prize": "德摩根奖",
    "Von Neumann Lecture": "冯·诺伊曼讲座",
    "George David Birkhoff Prize": "伯克霍夫奖",
    "Norbert Wiener Prize": "诺伯特·维纳奖",
    "Levi L. Conant Prize": "康南特奖",
    "Fulkerson Prize": "福克森奖",
    "Nemmers Prize in Mathematics": "内默斯数学奖",
    "Cantor Medal": "康托尔奖章",
    "Kant Lectureship": "康德讲座",
    "Kyoto Prize in Mathematics": "京都数学奖",
    "Stalin Prize, 2nd degree": "斯大林奖（二级）",
    "Saintour Prize": "圣图尔奖",
    "Petit d'Ormoy, Carriere, Thebault Award": "小多尔莫伊-卡里埃-泰博奖",
    "Heinz R. Pagels Human Rights of Scientists Award": "帕格斯科学家人权奖",
    "Q117478118": "未知奖项（Q117478118）",
    "Paul R. Halmos - Lester R. Ford Awards": "哈尔莫斯-福特写作奖",
    "James Madison Medal": "詹姆斯·麦迪逊奖章",
    "King Faisal International Prize in Science": "费萨尔国王国际科学奖",
    "Grand Prize of the French Academy of Science": "法兰西科学院大奖",
    "Royal Society Bakerian Medal": "皇家学会贝克讲座奖章",
    "Corresponding Member of the Australian Academy of Science": "澳大利亚科学院通讯院士",
    "Fellow of the Royal Society of Edinburgh": "爱丁堡皇家学会会士",
    "Grand Cross of the Legion of Honour": "荣誉军团大十字勋位",
    "honorary degree": "荣誉学位",
    "CNRS Gold medal": "CNRS 金质奖章",
    "Grand Officer of the Legion of Honour": "荣誉军团大官佐勋位",
    "Grand Cross of the National Order of Merit": "国家功绩勋章大十字勋位",
}

# 模式翻译（后缀匹配）
PATTERNS = [
    (r"^honorary doctorate from the (.+)$", "荣誉博士（\\1）"),
    (r"^honorary doctorate of the (.+)$", "荣誉博士（\\1）"),
    (r"^honorary doctorate from (.+)$", "荣誉博士（\\1）"),
    (r"^honorary doctorate of (.+)$", "荣誉博士（\\1）"),
    (r"^honorary doctor of the (.+)$", "荣誉博士（\\1）"),
    (r"^honorary doctor of (.+)$", "荣誉博士（\\1）"),
    (r"^honorary doctor from (.+)$", "荣誉博士（\\1）"),
    (r"^doctor honoris causa from the (.+)$", "荣誉博士（\\1）"),
    (r"^doctor honoris causa of the (.+)$", "荣誉博士（\\1）"),
    (r"^Doctor honoris causa from (.+)$", "荣誉博士（\\1）"),
    (r"^honorary doctor of the University of (.+)$", "\\1 大学荣誉博士"),
]


def main():
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("SELECT id, name_en, name_zh FROM awards WHERE name_zh=name_en OR name_zh IS NULL")
    rows = cur.fetchall()
    updated = 0
    remaining = []
    for aid, en, zh in rows:
        new_zh = None
        if en in EXACT:
            new_zh = EXACT[en]
        else:
            for pat, repl in PATTERNS:
                m = re.match(pat, en)
                if m:
                    new_zh = re.sub(pat, repl, en)
                    break
        if new_zh:
            cur.execute("UPDATE awards SET name_zh=%s WHERE id=%s", (new_zh, aid))
            updated += 1
            print(f"  {en} → {new_zh}")
        else:
            remaining.append(en)
    conn.commit()
    print(f"\n已更新: {updated}")
    if remaining:
        print(f"\n⚠ 仍缺中文名 ({len(remaining)}):")
        for r in remaining:
            print("   ", r)
    cur.execute("SELECT COUNT(*) FROM awards WHERE name_zh=name_zh AND name_zh <> ''")
    conn.close()


if __name__ == "__main__":
    main()
