# -*- coding: utf-8 -*-
"""OpenEcon 名录数据：诺贝尔经济学奖 1969–2025。

DATA = {年份: (获奖理由英文, 获奖理由中文, [(姓名en, 姓名zh, 国籍), ...])}
获奖理由为 Nobel 官方 citation（经维基百科表格清洗：去尾部引注与包裹引号）；
多数年份全年份共享理由；拆分理由年份（2000 / 2002 / 2003 / 2009 / 2021 / 2025）
用 "||" 分隔，顺序与获奖者一一对应，并在 generate_economics_list.py 的
GROUP_SIZES 中登记分组大小。国籍沿用维基百科表格 country 口径（多国籍按 " / " 连接）。
"""

US = "United States"
UK = "United Kingdom"

DATA = {
    1969: ("for having developed and applied dynamic models for the analysis of economic processes",
           "表彰他们为经济过程分析开发并应用了动态模型",
           [("Ragnar Frisch", "拉格纳·弗里施", "Norway"),
            ("Jan Tinbergen", "扬·廷贝亨", "Netherlands")]),
    1970: ("for the scientific work through which he has developed static and dynamic economic theory and actively contributed to raising the level of analysis in economic science",
           "表彰他发展静态与动态经济理论的科学工作，并积极推动经济科学分析水平的提升",
           [("Paul Samuelson", "保罗·萨缪尔森", US)]),
    1971: ("for his empirically founded interpretation of economic growth which has led to new and deepened insight into the economic and social structure and process of development",
           "表彰他对经济增长的实证性阐释，使人们对经济与社会结构及发展过程有了更新、更深的认识",
           [("Simon Kuznets", "西蒙·库兹涅茨", US)]),
    1972: ("for their pioneering contributions to general economic equilibrium theory and welfare theory",
           "表彰他们在一般经济均衡理论与福利理论方面的开创性贡献",
           [("John Hicks", "约翰·希克斯", UK),
            ("Kenneth Arrow", "肯尼斯·阿罗", US)]),
    1973: ("for the development of the input-output method and for its application to important economic problems",
           "表彰他发展了投入产出方法并将其应用于重要经济问题",
           [("Wassily Leontief", "华西里·列昂惕夫", "Soviet Union / United States")]),
    1974: ("for their pioneering work in the theory of money and economic fluctuations and for their penetrating analysis of the interdependence of economic, social and institutional phenomena",
           "表彰他们在货币理论与经济波动理论方面的开创性工作，以及对经济、社会与制度现象相互依存关系的深刻分析",
           [("Gunnar Myrdal", "贡纳尔·缪尔达尔", "Sweden"),
            ("Friedrich Hayek", "弗里德里希·哈耶克", "Austria / United Kingdom")]),
    1975: ("for their contributions to the theory of optimum allocation of resources",
           "表彰他们对资源最优配置理论的贡献",
           [("Leonid Kantorovich", "列昂尼德·康托罗维奇", "Soviet Union"),
            ("Tjalling Koopmans", "佳林·库普曼斯", "Netherlands / United States")]),
    1976: ("for his achievements in the fields of consumption analysis, monetary history and theory and for his demonstration of the complexity of stabilisation policy",
           "表彰他在消费分析、货币史与货币理论领域的成就，以及他对稳定化政策复杂性的论证",
           [("Milton Friedman", "米尔顿·弗里德曼", US)]),
    1977: ("for their pathbreaking contribution to the theory of international trade and international capital movements",
           "表彰他们对国际贸易与国际资本流动理论的开创性贡献",
           [("Bertil Ohlin", "贝蒂尔·奥林", "Sweden"),
            ("James Meade", "詹姆斯·米德", UK)]),
    1978: ("for his pioneering research into the decision-making process within economic organizations",
           "表彰他对经济组织内部决策过程的开创性研究",
           [("Herbert A. Simon", "赫伯特·西蒙", US)]),
    1979: ("for their pioneering research into economic development research with particular consideration of the problems of developing countries",
           "表彰他们对经济发展的开创性研究，尤其着重考虑了发展中国家的问题",
           [("Theodore Schultz", "西奥多·舒尔茨", US),
            ("W. Arthur Lewis", "威廉·阿瑟·刘易斯", "Saint Lucia / United Kingdom")]),
    1980: ("for the creation of econometric models and the application to the analysis of economic fluctuations and economic policies",
           "表彰他创建经济计量模型并将其应用于经济波动与经济政策分析",
           [("Lawrence Klein", "劳伦斯·克莱因", US)]),
    1981: ("for his analysis of financial markets and their relations to expenditure decisions, employment, production and prices",
           "表彰他对金融市场及其与支出决策、就业、生产和价格关系的分析",
           [("James Tobin", "詹姆斯·托宾", US)]),
    1982: ("for his seminal studies of industrial structures, functioning of markets and causes and effects of public regulation",
           "表彰他对产业结构、市场运作以及公共监管的成因与效果的开创性研究",
           [("George Stigler", "乔治·斯蒂格勒", US)]),
    1983: ("for having incorporated new analytical methods into economic theory and for his rigorous reformulation of the theory of general equilibrium",
           "表彰他将新的分析方法引入经济理论，并对一般均衡理论作出了严格的重构",
           [("Gérard Debreu", "杰拉尔·德布勒", "France")]),
    1984: ("for having made fundamental contributions to the development of systems of national accounts and hence greatly improved the basis for empirical economic analysis",
           "表彰他对国民经济核算体系发展的奠基性贡献，从而极大改善了实证经济分析的基础",
           [("Richard Stone", "理查德·斯通", UK)]),
    1985: ("for his pioneering analyses of saving and of financial markets",
           "表彰他对储蓄与金融市场的开创性分析",
           [("Franco Modigliani", "弗兰科·莫迪利安尼", "Italy")]),
    1986: ("for his development of the contractual and constitutional bases for the theory of economic and political decision-making",
           "表彰他为经济与政治决策理论奠定了契约与宪制基础",
           [("James M. Buchanan", "詹姆斯·布坎南", US)]),
    1987: ("for his contributions to the theory of economic growth",
           "表彰他对经济增长理论的贡献",
           [("Robert Solow", "罗伯特·索洛", US)]),
    1988: ("for his pioneering contributions to the theory of markets and efficient utilization of resources",
           "表彰他对市场理论与资源有效利用理论的开创性贡献",
           [("Maurice Allais", "莫里斯·阿莱", "France")]),
    1989: ("for his clarification of the probability theory foundations of econometrics and his analyses of simultaneous economic structures",
           "表彰他阐明了经济计量学的概率论基础，并对联立经济结构进行了分析",
           [("Trygve Haavelmo", "特里夫·哈维默", "Norway")]),
    1990: ("for their pioneering work in the theory of financial economics",
           "表彰他们在金融经济学理论方面的开创性工作",
           [("Harry Markowitz", "哈里·马科维茨", US),
            ("Merton Miller", "默顿·米勒", US),
            ("William F. Sharpe", "威廉·夏普", US)]),
    1991: ("for his discovery and clarification of the significance of transaction costs and property rights for the institutional structure and functioning of the economy",
           "表彰他发现并阐明了交易成本和产权对经济制度结构与运行的重要意义",
           [("Ronald Coase", "罗纳德·科斯", UK)]),
    1992: ("for having extended the domain of microeconomic analysis to a wide range of human behaviour and interaction, including non-market behaviour",
           "表彰他将微观经济分析的领域扩展到包括非市场行为在内的人类行为与互动的广泛范围",
           [("Gary Becker", "加里·贝克尔", US)]),
    1993: ("for having renewed research in economic history by applying economic theory and quantitative methods in order to explain economic and institutional change",
           "表彰他们运用经济理论与量化方法重新开展经济史研究，以解释经济与制度变迁",
           [("Robert Fogel", "罗伯特·福格尔", US),
            ("Douglass North", "道格拉斯·诺思", US)]),
    1994: ("for their pioneering analysis of equilibria in the theory of non-cooperative games",
           "表彰他们在非合作博弈理论中关于均衡的开创性分析",
           [("John Harsanyi", "约翰·海萨尼", "Hungary / United States"),
            ("John Forbes Nash Jr.", "小约翰·福布斯·纳什", US),
            ("Reinhard Selten", "莱因哈德·泽尔腾", "Germany")]),
    1995: ("for having developed and applied the hypothesis of rational expectations, and thereby having transformed macroeconomic analysis and deepened our understanding of economic policy",
           "表彰他提出并应用理性预期假说，从而改变了宏观经济分析并深化了人们对经济政策的理解",
           [("Robert Lucas, Jr.", "罗伯特·卢卡斯", US)]),
    1996: ("for their fundamental contributions to the economic theory of incentives under asymmetric information",
           "表彰他们对不对称信息下激励经济理论的基础性贡献",
           [("James Mirrlees", "詹姆斯·莫里斯", UK),
            ("William Vickrey", "威廉·维克里", "Canada / United States")]),
    1997: ("for a new method to determine the value of derivatives",
           "表彰他们提出了确定衍生品价值的新方法",
           [("Robert C. Merton", "罗伯特·默顿", US),
            ("Myron Scholes", "迈伦·斯科尔斯", "Canada / United States")]),
    1998: ("for his contributions to welfare economics",
           "表彰他对福利经济学的贡献",
           [("Amartya Sen", "阿马蒂亚·森", "India")]),
    1999: ("for his analysis of monetary and fiscal policy under different exchange rate regimes and his analysis of optimum currency areas",
           "表彰他对不同汇率制度下货币与财政政策的分析，以及对最优货币区域的分析",
           [("Robert Mundell", "罗伯特·蒙代尔", "Canada")]),
    2000: ("for his development of theory and methods for analyzing selective samples||for his development of theory and methods for analyzing discrete choice",
           "表彰他发展了分析选择性样本的理论与方法||表彰他发展了分析离散选择的理论与方法",
           [("James Heckman", "詹姆斯·赫克曼", US),
            ("Daniel McFadden", "丹尼尔·麦克法登", US)]),
    2001: ("for their analyses of markets with information asymmetry",
           "表彰他们对信息不对称市场的分析",
           [("George Akerlof", "乔治·阿克洛夫", US),
            ("Michael Spence", "迈克尔·斯宾塞", US),
            ("Joseph Stiglitz", "约瑟夫·斯蒂格利茨", US)]),
    2002: ("for having integrated insights from psychological research into economic science, especially concerning human judgment and decision-making under uncertainty||for having established laboratory experiments as a tool in empirical economic analysis, especially in the study of alternative market mechanisms",
           "表彰他将心理学研究的洞见融入经济科学，特别是关于不确定条件下的人类判断与决策||表彰他将实验室实验确立为实证经济分析的工具，尤其是对各种市场机制的研究",
           [("Daniel Kahneman", "丹尼尔·卡尼曼", "United States / Israel"),
            ("Vernon L. Smith", "弗农·史密斯", US)]),
    2003: ("for methods of analyzing economic time series with time-varying volatility (ARCH)||for methods of analyzing economic time series with common trends (cointegration)",
           "表彰他提出了分析具有时变波动性的经济时间序列的方法（ARCH）||表彰他提出了分析具有共同趋势的经济时间序列的方法（协整）",
           [("Robert F. Engle", "罗伯特·恩格尔", US),
            ("Clive Granger", "克莱夫·格兰杰", UK)]),
    2004: ("for their contributions to dynamic macroeconomics: the time consistency of economic policy and the driving forces behind business cycles",
           "表彰他们对动态宏观经济学的贡献：经济政策的时间一致性与经济周期背后的驱动力量",
           [("Finn E. Kydland", "芬恩·基德兰德", "Norway"),
            ("Edward C. Prescott", "爱德华·普雷斯科特", US)]),
    2005: ("for having enhanced our understanding of conflict and cooperation through game-theory analysis",
           "表彰他们通过博弈论分析增进了我们对冲突与合作的理解",
           [("Robert Aumann", "罗伯特·奥曼", "United States / Israel"),
            ("Thomas Schelling", "托马斯·谢林", US)]),
    2006: ("for his analysis of intertemporal tradeoffs in macroeconomic policy",
           "表彰他对宏观经济政策中跨期权衡的分析",
           [("Edmund Phelps", "埃德蒙·费尔普斯", US)]),
    2007: ("for having laid the foundations of mechanism design theory",
           "表彰他们奠定了机制设计理论的基础",
           [("Leonid Hurwicz", "莱昂尼德·赫维奇", "Poland / United States"),
            ("Eric Maskin", "埃里克·马斯金", US),
            ("Roger Myerson", "罗杰·迈尔森", US)]),
    2008: ("for his analysis of trade patterns and location of economic activity",
           "表彰他对贸易模式与经济活动区位的分析",
           [("Paul Krugman", "保罗·克鲁格曼", US)]),
    2009: ("for her analysis of economic governance, especially the commons||for his analysis of economic governance, especially the boundaries of the firm",
           "表彰她对经济治理尤其是公共资源的分析||表彰他对经济治理尤其是企业边界的分析",
           [("Elinor Ostrom", "埃莉诺·奥斯特罗姆", US),
            ("Oliver E. Williamson", "奥利弗·威廉姆森", US)]),
    2010: ("for their analysis of markets with search frictions",
           "表彰他们对存在搜寻摩擦的市场的分析",
           [("Peter Diamond", "彼得·戴蒙德", US),
            ("Dale T. Mortensen", "戴尔·莫滕森", US),
            ("Christopher A. Pissarides", "克里斯托弗·皮萨里德斯", "Cyprus / United Kingdom")]),
    2011: ("for their empirical research on cause and effect in the macroeconomy",
           "表彰他们对宏观经济中因果关系的实证研究",
           [("Thomas J. Sargent", "托马斯·萨金特", US),
            ("Christopher A. Sims", "克里斯托弗·西姆斯", US)]),
    2012: ("for the theory of stable allocations and the practice of market design",
           "表彰他们关于稳定配置的理论与市场设计的实践",
           [("Alvin E. Roth", "阿尔文·罗思", US),
            ("Lloyd Shapley", "劳埃德·沙普利", US)]),
    2013: ("for their empirical analysis of asset prices",
           "表彰他们对资产价格的实证分析",
           [("Eugene Fama", "尤金·法马", US),
            ("Lars Peter Hansen", "拉尔斯·彼得·汉森", US),
            ("Robert J. Shiller", "罗伯特·希勒", US)]),
    2014: ("for his analysis of market power and regulation",
           "表彰他对市场力量与监管的分析",
           [("Jean Tirole", "让·梯若尔", "France")]),
    2015: ("for his analysis of consumption, poverty, and welfare",
           "表彰他对消费、贫困与福利的分析",
           [("Angus Deaton", "安格斯·迪顿", "United Kingdom / United States")]),
    2016: ("for their contributions to contract theory",
           "表彰他们对契约理论的贡献",
           [("Oliver Hart", "奥利弗·哈特", "United Kingdom / United States"),
            ("Bengt Holmström", "本特·霍姆斯特罗姆", "Finland")]),
    2017: ("for his contributions to behavioural economics",
           "表彰他对行为经济学的贡献",
           [("Richard Thaler", "理查德·塞勒", US)]),
    2018: ("for integrating climate change into long-run macroeconomic analysis||for integrating technological innovations into long-run macroeconomic analysis",
           "表彰他将气候变化纳入长期宏观经济分析||表彰他将技术创新纳入长期宏观经济分析",
           [("William Nordhaus", "威廉·诺德豪斯", US),
            ("Paul Romer", "保罗·罗默", US)]),
    2019: ("for their experimental approach to alleviating global poverty",
           "表彰他们以实验性方法减轻全球贫困",
           [("Abhijit Banerjee", "阿比吉特·班纳吉", "India / United States"),
            ("Esther Duflo", "埃丝特·迪弗洛", "France / United States"),
            ("Michael Kremer", "迈克尔·克雷默", US)]),
    2020: ("for improvements to auction theory and inventions of new auction formats",
           "表彰他们对拍卖理论的改进以及新拍卖形式的发明",
           [("Paul Milgrom", "保罗·米尔格罗姆", US),
            ("Robert B. Wilson", "罗伯特·威尔逊", US)]),
    2021: ("for his empirical contributions to labour economics||for their methodological contributions to the analysis of causal relationships",
           "表彰他对劳动经济学的实证贡献||表彰他们对因果关系分析方法论的贡献",
           [("David Card", "戴维·卡德", "Canada / United States"),
            ("Joshua Angrist", "约书亚·安格里斯特", "United States / Israel"),
            ("Guido Imbens", "吉多·因本斯", "United States / Netherlands")]),
    2022: ("for research on banks and financial crises",
           "表彰他们关于银行与金融危机的研究",
           [("Ben Bernanke", "本·伯南克", US),
            ("Douglas Diamond", "道格拉斯·戴蒙德", US),
            ("Philip H. Dybvig", "菲利普·迪布维格", US)]),
    2023: ("for having advanced our understanding of women's labour market outcomes",
           "表彰她增进了我们对女性劳动力市场表现的理解",
           [("Claudia Goldin", "克劳迪娅·戈尔丁", US)]),
    2024: ("for studies of how institutions are formed and affect prosperity",
           "表彰他们关于制度如何形成并影响繁荣的研究",
           [("Daron Acemoglu", "达龙·阿西莫格鲁", "Turkey / United States"),
            ("Simon Johnson", "西蒙·约翰逊", "United Kingdom / United States"),
            ("James A. Robinson", "詹姆斯·罗宾逊", "United Kingdom / United States")]),
    2025: ("for having identified the prerequisites for sustained growth through technological progress||for the theory of sustained growth through creative destruction",
           "表彰他识别了通过技术进步实现持续增长的前提条件||表彰他们关于通过创造性破坏实现持续增长的理论",
           [("Joel Mokyr", "乔尔·莫基尔", "United States / Israel"),
            ("Philippe Aghion", "菲利普·阿吉翁", "France"),
            ("Peter Howitt", "彼得·豪伊特", "Canada")]),
}

# 女性得主（截至 2025）
FEMALE_20TH: set[str] = set()  # 1969–2000 无女性得主
FEMALE_21TH = {"Elinor Ostrom", "Esther Duflo", "Claudia Goldin"}
