# -*- coding: utf-8 -*-
"""OpenPeace 名录数据：诺贝尔和平奖 1901–2025。

DATA = {年份: (获奖理由英文, 获奖理由中文, [(获奖者en, 获奖者zh, 国家/机构), ...])}
获奖理由为英文维基百科「List of Nobel Peace Prize laureates」所载 citation（去掉脚注）；
共享理由年份为全年份共通；按人拆分理由的年份（1901/1902/1907/1911/1925/1946/1974）
用 "||" 分隔，顺序与获奖者一一对应。
国籍沿用维基表格口径（个人为获奖时国籍；跨国/政府间组织统一标 International
organization，国家级机构保留所在国）。
组织机构获奖者：红十字国际委员会（1917、1944、1963 三度）、联合国难民署（1954、1981
两度）按多次获奖分别列行。
"""

US = "United States"
UK = "United Kingdom"
ORG = "International organization"

DATA = {
    1901: ("for his humanitarian efforts to help wounded soldiers and create international understanding || for his lifelong work for international peace conferences, diplomacy and arbitration.",
           "表彰他为救助伤员、增进国际理解所做出的人道主义努力 || 表彰他毕生致力于国际和平会议、外交与仲裁事业",
           [("Henry Dunant", "亨利·杜南", "Switzerland"),
            ("Frédéric Passy", "弗雷德里克·帕西", "France")]),
    1902: ("for his untiring and skilful directorship of the Bern Peace Bureau || for his eminently practical administration of the Inter-Parliamentary Union.",
           "表彰他不知疲倦且娴熟地领导伯尔尼国际和平局 || 表彰他对各国议会联盟卓有实效的管理",
           [("Élie Ducommun", "埃利·迪科门", "Switzerland"),
            ("Charles Albert Gobat", "夏尔·阿尔贝·戈巴", "Switzerland")]),
    1903: ("for his longstanding and devoted effort in favour of the ideas of peace and arbitration.",
           "表彰他长期不懈地倡导和平与仲裁理念",
           [("William Randal Cremer", "威廉·兰德尔·克里默", UK)]),
    1904: ("for its striving in public law to develop peaceful ties between nations and to make the laws of war more humane.",
           "表彰该机构致力于发展公法以促进国家间和平关系，并推动战争法规更加人道化",
           [("Institute of International Law", "国际法研究院", "Belgium")]),
    1905: ("for her audacity to oppose the horrors of war.",
           "表彰她敢于直面并反对战争的恐怖",
           [("Bertha von Suttner", "贝尔塔·冯·苏特纳", "Austria-Hungary")]),
    1906: ("for his role in bringing to an end the bloody war recently waged between two of the world's great powers, Japan and Russia.",
           "表彰他促成当时世界上两大强国日本与俄国之间血腥战争的终结",
           [("Theodore Roosevelt", "西奥多·罗斯福", US)]),
    1907: ("for his work in the press and in peace meetings, both public and private, for an understanding between France and Italy || for his decisive influence upon the conduct and outcome of the Hague and Geneva Conferences.",
           "表彰他通过新闻与和平集会（无论公开或私下）推动法国与意大利之间的相互理解 || 表彰他对海牙会议与日内瓦会议的进程和成果发挥了决定性影响",
           [("Ernesto Teodoro Moneta", "埃内斯托·泰奥多罗·莫内塔", "Italy"),
            ("Louis Renault", "路易·勒诺", "France")]),
    1908: ("for their long time work for the cause of peace as politicians, peace society leaders, orators and authors.",
           "表彰他们以政治家、和平团体领导人、演说家与作家的身份长期为和平事业工作",
           [("Klas Pontus Arnoldson", "克拉斯·蓬图斯·阿诺尔德松", "Sweden"),
            ("Fredrik Bajer", "弗雷德里克·巴耶", "Denmark")]),
    1909: ("for their prominent position in the international movement for peace and arbitration.",
           "表彰他们在国际和平与仲裁运动中的杰出地位",
           [("Auguste Beernaert", "奥古斯特·贝尔纳特", "Belgium"),
            ("Paul Henri d'Estournelles de Constant", "保罗·亨利·德埃斯特尔内勒·德·康斯坦", "France")]),
    1910: ("for acting as a link between the peace societies of the various countries, and helping them to organize the world rallies of the international peace movement.",
           "表彰它作为各国和平团体之间的纽带，协助组织国际和平运动的世界性集会",
           [("Permanent International Peace Bureau", "国际和平局", ORG)]),
    1911: ("for his role as co-founder of the Institut de droit international, initiator of the Conferences on International Private Law at the Hague, and pioneer in the field of international legal relations || for his effort to expose and fight what he considers to be the main cause of war, namely, the anarchy in international relations.",
           "表彰他作为国际法研究院共同创始人、海牙国际私法会议发起人，以及国际法律关系领域的开拓者 || 表彰他揭露并抗争其所认为的战争主要根源——国际关系中的无政府状态",
           [("Tobias Asser", "托比亚斯·阿塞尔", "Netherlands"),
            ("Alfred Fried", "阿尔弗雷德·弗里德", "Austria-Hungary")]),
    1912: ("for bringing about better understanding between the countries of North and South America and initiating important arbitration agreements between the United States and other countries.",
           "表彰他促进南北美洲各国之间的相互理解，并促成美国与其他国家间的重要仲裁协定",
           [("Elihu Root", "伊莱休·鲁特", US)]),
    1913: ("for his unparalleled contribution to the organization of peaceful internationalism.",
           "表彰他对和平国际主义组织建设的无与伦比的贡献",
           [("Henri La Fontaine", "亨利·拉方丹", "Belgium")]),
    1917: ("for the efforts to take care of wounded soldiers and prisoners of war and their families.",
           "表彰其为照顾伤兵、战俘及其家属所付出的努力",
           [("International Committee of the Red Cross", "红十字国际委员会", ORG)]),
    1919: ("for his role as founder of the League of Nations.",
           "表彰他作为国际联盟缔造者所发挥的作用",
           [("Woodrow Wilson", "伍德罗·威尔逊", US)]),
    1920: ("for his longstanding contribution to the cause of peace and justice and his prominent role in the establishment of the League of Nations.",
           "表彰他长期致力于和平与正义事业，并在创建国际联盟中发挥的突出作用",
           [("Léon Bourgeois", "莱昂·布尔茹瓦", "France")]),
    1921: ("for their lifelong contributions to the cause of peace and organized internationalism.",
           "表彰他们毕生对和平事业与有组织的国际主义的贡献",
           [("Hjalmar Branting", "亚尔马·布兰廷", "Sweden"),
            ("Christian Lange", "克里斯蒂安·朗格", "Norway")]),
    1922: ("for his leading role in the repatriation of prisoners of war, in international relief work and as the League of Nations' High Commissioner for refugees.",
           "表彰他在战俘遣返与国际救援工作中的领导作用，以及担任国际联盟难民事务高级专员的贡献",
           [("Fridtjof Nansen", "弗里乔夫·南森", "Norway")]),
    1925: ("for his crucial role in bringing about the Locarno Treaty || for his crucial role in bringing about the Dawes Plan.",
           "表彰他在促成《洛迦诺公约》中的关键作用 || 表彰他在促成《道威斯计划》中的关键作用",
           [("Sir Austen Chamberlain", "奥斯汀·张伯伦爵士", UK),
            ("Charles G. Dawes", "查尔斯·G·道威斯", US)]),
    1926: ("for their crucial role in bringing about the Locarno Treaty.",
           "表彰他们在促成《洛迦诺公约》中的关键作用",
           [("Aristide Briand", "阿里斯蒂德·白里安", "France"),
            ("Gustav Stresemann", "古斯塔夫·施特雷泽曼", "Germany")]),
    1927: ("for their contribution to the emergence in France and Germany of a public opinion which favours peaceful international cooperation.",
           "表彰他们为法德两国形成支持和平国际合作的社会舆论做出的贡献",
           [("Ferdinand Buisson", "费迪南·比松", "France"),
            ("Ludwig Quidde", "路德维希·克维德", "Germany")]),
    1929: ("for his crucial role in bringing about the Kellogg-Briand Pact.",
           "表彰他在促成《凯洛格—白里安公约》（《非战公约》）中的关键作用",
           [("Frank Billings Kellogg", "弗兰克·比林斯·凯洛格", US)]),
    1930: ("for promoting Christian unity and helping create 'that new attitude of mind which is necessary if peace between nations is to become reality'.",
           "表彰他推动基督教会的合一，并帮助培育“若要国家间和平成为现实所必需的那种新心态”",
           [("Nathan Söderblom", "纳坦·瑟德布卢姆", "Sweden")]),
    1931: ("for their assiduous effort to revive the ideal of peace and to rekindle the spirit of peace in their own nation and in the whole of mankind.",
           "表彰他们不懈努力重振和平理想，在本国乃至全人类心中重新点燃和平精神",
           [("Jane Addams", "简·亚当斯", US),
            ("Nicholas Murray Butler", "尼古拉斯·默里·巴特勒", US)]),
    1933: ("for having exposed by his pen the illusion of war and presented a convincing plea for international cooperation and peace.",
           "表彰他以笔揭露战争的幻象，并为国际合作与和平提出令人信服的呼吁",
           [("Sir Norman Angell", "诺曼·安吉尔爵士", UK)]),
    1934: ("for his untiring struggle and his courageous efforts as Chairman of the League of Nations Disarmament Conference 1931-34.",
           "表彰他作为 1931–1934 年国际联盟裁军会议主席所进行的不懈斗争与勇敢努力",
           [("Arthur Henderson", "阿瑟·亨德森", UK)]),
    1935: ("for his burning love for freedom of thought and expression and his valuable contribution to the cause of peace.",
           "表彰他对思想自由与言论自由的炽热之爱，以及他对和平事业的宝贵贡献",
           [("Carl von Ossietzky", "卡尔·冯·奥西茨基", "Germany")]),
    1936: ("for his role as father of the Argentine Antiwar Pact of 1933, which he also used as a means to mediate peace between Paraguay and Bolivia in 1935.",
           "表彰他作为 1933 年《阿根廷反战公约》缔造者的角色，并借此于 1935 年在巴拉圭与玻利维亚之间斡旋和平",
           [("Carlos Saavedra Lamas", "卡洛斯·萨维德拉·拉马斯", "Argentina")]),
    1937: ("for his tireless effort in support of the League of Nations, disarmament and peace.",
           "表彰他为支持国际联盟、裁军与和平所做的不倦努力",
           [("The Viscount Cecil of Chelwood", "塞西尔子爵（罗伯特·塞西尔）", UK)]),
    1938: ("for having carried on the work of Fridtjof Nansen to the benefit of refugees across Europe.",
           "表彰它继承弗里乔夫·南森的事业，惠及全欧洲的难民",
           [("Nansen International Office for Refugees", "南森国际难民办公室", ORG)]),
    1944: ("for the great work it has performed during the war on behalf of humanity.",
           "表彰它在战争期间为人道事业所做的卓越工作",
           [("International Committee of the Red Cross", "红十字国际委员会", ORG)]),
    1945: ("for his indefatigable work for international understanding and his pivotal role in establishing the United Nations.",
           "表彰他不知疲倦地促进国际理解，并在创建联合国中发挥的关键作用",
           [("Cordell Hull", "科德尔·赫尔", US)]),
    1946: ("for her lifelong work for the cause of peace || for his contribution to the creation of a peace-promoting religious brotherhood across national boundaries.",
           "表彰她毕生为和平事业所做的工作 || 表彰他为创建跨越国界、促进和平的宗教兄弟会所做的贡献",
           [("Emily Greene Balch", "艾米莉·格林·巴尔奇", US),
            ("John Raleigh Mott", "约翰·雷利·马特", US)]),
    1947: ("for their pioneering work in the international peace movement and compassionate effort to relieve human suffering, thereby promoting the fraternity between nations.",
           "表彰它们在国际和平运动中的开创性工作与减轻人类苦难的仁爱努力，从而促进各国人民之间的友爱",
           [("Friends Service Council", "公谊服务理事会", UK),
            ("American Friends Service Committee", "美国公谊服务委员会", US)]),
    1949: ("for his lifelong effort to conquer hunger and want, thereby helping to remove a major cause of military conflict and war.",
           "表彰他毕生致力于战胜饥饿与匮乏，从而帮助消除军事冲突与战争的一大根源",
           [("Lord Boyd-Orr", "博伊德-奥尔男爵（约翰·博伊德·奥尔）", UK)]),
    1950: ("for his work as mediator in Palestine in 1948-1949.",
           "表彰他在 1948–1949 年担任巴勒斯坦调停者的工作",
           [("Ralph Bunche", "拉尔夫·邦奇", US)]),
    1951: ("for having devoted his life to the fight against war through the promotion of social justice and brotherhood among men and nations.",
           "表彰他毕生通过促进社会正义与人人、国国之间的友爱来抗击战争",
           [("Léon Jouhaux", "莱昂·茹奥", "France")]),
    1952: ("for his altruism, reverence for life, and tireless humanitarian work which has helped making the idea of brotherhood between men and nations a living one.",
           "表彰他的利他主义、敬畏生命的精神与不知疲倦的人道主义工作，使人人与国国之间手足情谊的理念成为现实",
           [("Albert Schweitzer", "阿尔贝特·施韦泽", "France")]),
    1953: ("for proposing and supervising the plan for the economic recovery of Europe.",
           "表彰他提出并主持欧洲经济复兴计划（马歇尔计划）",
           [("George Catlett Marshall Jr.", "乔治·卡特利特·马歇尔", US)]),
    1954: ("for its efforts to heal the wounds of war by providing help and protection to refugees all over the world.",
           "表彰它通过向全世界难民提供帮助与保护来治愈战争创伤的努力",
           [("Office of the United Nations High Commissioner for Refugees", "联合国难民事务高级专员公署", ORG)]),
    1957: ("for his crucial contribution to the deployment of a United Nations Emergency Force in the wake of the Suez Crisis.",
           "表彰他在苏伊士危机后为部署联合国紧急部队做出的关键贡献",
           [("Lester Bowles Pearson", "莱斯特·鲍尔斯·皮尔逊", "Canada")]),
    1958: ("for his efforts to help refugees to leave their camps and return to a life of freedom and dignity.",
           "表彰他帮助难民走出难民营、回归自由与尊严生活的不懈努力",
           [("Dominique Pire", "多米尼克·皮尔", "Belgium")]),
    1959: ("for his longstanding contribution to the cause of disarmament and peace.",
           "表彰他长期对裁军与和平事业的贡献",
           [("Philip Noel-Baker", "菲利普·诺埃尔-贝克", UK)]),
    1960: ("for his non-violent struggle against apartheid.",
           "表彰他以非暴力方式反对种族隔离制度的斗争",
           [("Albert Luthuli", "阿尔伯特·卢图利", "South Africa")]),
    1961: ("for developing the UN into an effective and constructive international organization, capable of giving life to the principles and aims expressed in the UN Charter.",
           "表彰他将联合国发展为一个能够践行《联合国宪章》原则与宗旨的、卓有成效的建设性国际组织",
           [("Dag Hammarskjöld", "达格·哈马舍尔德", "Sweden")]),
    1962: ("for his fight against the nuclear arms race between East and West.",
           "表彰他对抗东西方核军备竞赛的斗争",
           [("Linus Pauling", "莱纳斯·鲍林", US)]),
    1963: ("for promoting the principles of the Geneva Convention and cooperation with the UN.",
           "表彰其推广《日内瓦公约》原则并与联合国开展合作",
           [("International Committee of the Red Cross", "红十字国际委员会", ORG),
            ("League of Red Cross Societies", "红十字会协会", ORG)]),
    1964: ("for his non-violent struggle for civil rights for the Afro-American population.",
           "表彰他为美国黑人争取公民权利的非暴力斗争",
           [("Martin Luther King Jr.", "马丁·路德·金", US)]),
    1965: ("for its effort to enhance solidarity between nations and reduce the difference between rich and poor states.",
           "表彰其为增进国家间团结、缩小贫富国家差距所做的努力",
           [("United Nations Children's Fund (UNICEF)", "联合国儿童基金会", ORG)]),
    1968: ("for his struggle to ensure the rights of man as stipulated in the UN Declaration.",
           "表彰他为保障《世界人权宣言》所载人权而进行的斗争",
           [("René Cassin", "勒内·卡森", "France")]),
    1969: ("for creating international legislation insuring certain norms for working conditions in every country.",
           "表彰其创建国际劳工立法，保障各国劳动条件的特定标准",
           [("International Labour Organization", "国际劳工组织", ORG)]),
    1970: ("for having given a well-founded hope - the green revolution.",
           "表彰他带来了有充分依据的希望——绿色革命",
           [("Norman Ernest Borlaug", "诺曼·博洛格", US)]),
    1971: ("for paving the way for a meaningful dialogue between East and West.",
           "表彰他为东西方之间有意义的对话铺平了道路",
           [("Willy Brandt", "维利·勃兰特", "West Germany")]),
    1973: ("for jointly having negotiated a cease fire in Vietnam in 1973.",
           "表彰二人共同谈判达成 1973 年越南停火",
           [("Henry Kissinger", "亨利·基辛格", US),
            ("Lê Đức Thọ", "黎德寿", "North Vietnam")]),
    1974: ("for his efforts to secure and develop human rights throughout the world || for his contribution to stabilize conditions in the Pacific rim area and for signing the Nuclear Non-Proliferation Treaty.",
           "表彰他为在全世界保障与发展人权所做的努力 || 表彰他为稳定亚太地区局势做出的贡献以及签署《不扩散核武器条约》",
           [("Seán MacBride", "肖恩·麦克布赖德", "Ireland"),
            ("Eisaku Satō", "佐藤荣作", "Japan")]),
    1975: ("for his struggle for human rights in the Soviet Union, for disarmament and cooperation between all nations.",
           "表彰他为苏联人权、裁军以及各国间合作而进行的斗争",
           [("Andrei Sakharov", "安德烈·萨哈罗夫", "Soviet Union")]),
    1976: ("for the courageous efforts in founding a movement to put an end to the violent conflict in Northern Ireland.",
           "表彰她们为发起终止北爱尔兰暴力冲突运动所表现出的勇气",
           [("Betty Williams", "贝蒂·威廉斯", UK),
            ("Mairead Corrigan", "梅里德·科里根", UK)]),
    1977: ("for worldwide respect for human rights.",
           "表彰其为在全世界尊重人权所做的贡献",
           [("Amnesty International", "国际特赦组织", UK)]),
    1978: ("for jointly having negotiated peace between Egypt and Israel in 1978.",
           "表彰二人共同谈判促成 1978 年埃及与以色列之间的和平",
           [("Anwar Sadat", "安瓦尔·萨达特", "Egypt"),
            ("Menachem Begin", "梅纳赫姆·贝京", "Israel")]),
    1979: ("for her work for bringing help to suffering humanity.",
           "表彰她为救助苦难人类所做的工作",
           [("Mother Teresa", "特蕾莎修女", "Albania")]),
    1980: ("for being a source of inspiration to repressed people, especially in Latin America.",
           "表彰他成为受压迫民众（尤其是拉丁美洲民众）的精神源泉",
           [("Adolfo Pérez Esquivel", "阿道弗·佩雷斯·埃斯基维尔", "Argentina")]),
    1981: ("for promoting the fundamental rights of refugees.",
           "表彰其为维护难民基本权利所做的促进工作",
           [("Office of the United Nations High Commissioner for Refugees", "联合国难民事务高级专员公署", ORG)]),
    1982: ("for their work for disarmament and nuclear and weapon-free zones.",
           "表彰他们在裁军以及无核武器区与无武器区方面的工作",
           [("Alva Myrdal", "阿尔娃·米达尔", "Sweden"),
            ("Alfonso García Robles", "阿方索·加西亚·罗夫莱斯", "Mexico")]),
    1983: ("for non-violent struggle for free trade unions and human rights in Poland.",
           "表彰他为波兰自由工会与人权进行的非暴力斗争",
           [("Lech Wałęsa", "莱赫·瓦文萨", "Poland")]),
    1984: ("for his role as a unifying leader figure in the non-violent campaign to resolve the problem of apartheid in South Africa.",
           "表彰他作为统一性领袖人物，在以非暴力运动解决南非种族隔离问题中发挥的作用",
           [("Desmond Tutu", "德斯蒙德·图图", "South Africa")]),
    1985: ("for spreading authoritative information and by creating awareness of the catastrophic consequences of nuclear war.",
           "表彰其传播权威信息，唤醒世人对核战争灾难性后果的认识",
           [("International Physicians for the Prevention of Nuclear War", "国际防止核战争医生组织", ORG)]),
    1986: ("for being a messenger to mankind: his message is one of peace, atonement and dignity.",
           "表彰他作为人类的信使：他所传递的是和平、救赎与尊严的讯息",
           [("Elie Wiesel", "埃利·维瑟尔", US)]),
    1987: ("for his work for lasting peace in Central America.",
           "表彰他为中美洲持久和平所做的工作",
           [("Óscar Arias", "奥斯卡·阿里亚斯", "Costa Rica")]),
    1988: ("for preventing armed clashes and creating conditions for negotiations.",
           "表彰其防止武装冲突并为谈判创造条件",
           [("United Nations Peace-Keeping Forces", "联合国维持和平部队", ORG)]),
    1989: ("for advocating peaceful solutions based upon tolerance and mutual respect in order to preserve the historical and cultural heritage of his people.",
           "表彰其倡导以宽容与相互尊重为基础的和平方式，以维护本民族的历史与文化遗产",
           [("Tenzin Gyatso, 14th Dalai Lama", "第十四世达赖喇嘛·丹增嘉措", "India")]),
    1990: ("for the leading role he played in the radical changes in East-West relations.",
           "表彰他在东西方关系剧变中所发挥的主导作用",
           [("Mikhail Gorbachev", "米哈伊尔·戈尔巴乔夫", "Soviet Union")]),
    1991: ("for her non-violent struggle for democracy and human rights.",
           "表彰她为民主与人权进行的非暴力斗争",
           [("Aung San Suu Kyi", "昂山素季", "Myanmar")]),
    1992: ("for her struggle for social justice and ethno-cultural reconciliation based on respect for the rights of indigenous peoples.",
           "表彰她基于尊重原住民权利、为社会正义与族裔文化和解而进行的斗争",
           [("Rigoberta Menchú", "里戈韦塔·门楚", "Guatemala")]),
    1993: ("for their work for the peaceful termination of the apartheid regime, and for laying the foundations for a new democratic South Africa.",
           "表彰他们和平终结种族隔离制度的工作，以及为新民主南非奠定基础",
           [("Nelson Mandela", "纳尔逊·曼德拉", "South Africa"),
            ("Frederik Willem de Klerk", "弗雷德里克·威廉·德克勒克", "South Africa")]),
    1994: ("for their efforts to create peace in the Middle East.",
           "表彰他们为在中东缔造和平所做的努力",
           [("Yasser Arafat", "亚西尔·阿拉法特", "Palestine"),
            ("Yitzhak Rabin", "伊扎克·拉宾", "Israel"),
            ("Shimon Peres", "希蒙·佩雷斯", "Israel")]),
    1995: ("for their efforts to diminish the part played by nuclear arms in international politics and, in the longer run, to eliminate such arms.",
           "表彰他们为削弱核武器在国际政治中的作用、并在长远上消除核武器所做的努力",
           [("Joseph Rotblat", "约瑟夫·罗特布拉特", "Poland"),
            ("Pugwash Conferences on Science and World Affairs", "帕格沃什科学与世界事务会议", ORG)]),
    1996: ("for their work towards a just and peaceful solution to the conflict in East Timor.",
           "表彰他们为公正和平地解决东帝汶冲突所做的工作",
           [("Carlos Filipe Ximenes Belo", "卡洛斯·菲利佩·西门内斯·贝洛", "East Timor"),
            ("José Ramos-Horta", "若泽·拉莫斯·奥尔塔", "East Timor")]),
    1997: ("for their work for the banning and clearing of anti-personnel mines.",
           "表彰他们为禁止与清除杀伤人员地雷所做的工作",
           [("International Campaign to Ban Landmines", "国际禁止地雷运动", ORG),
            ("Jody Williams", "乔迪·威廉斯", US)]),
    1998: ("for their efforts to find a peaceful solution to the conflict in Northern Ireland.",
           "表彰他们为和平解决北爱尔兰冲突所做的努力",
           [("John Hume", "约翰·休姆", "Ireland"),
            ("David Trimble", "大卫·特林布尔", UK)]),
    1999: ("in recognition of the organization's pioneering humanitarian work on several continents.",
           "表彰该组织在多个大洲的开创性人道主义工作",
           [("Médecins Sans Frontières", "无国界医生", ORG)]),
    2000: ("for his work for democracy and human rights in South Korea and in East Asia in general, and for peace and reconciliation with North Korea in particular.",
           "表彰他为韩国及整个东亚的民主与人权所做的工作，尤其是为与朝鲜的和平和解所做的努力",
           [("Kim Dae-jung", "金大中", "South Korea")]),
    2001: ("for their work for a better organized and more peaceful world.",
           "表彰他们为一个组织更完善、更和平的世界所做的工作",
           [("United Nations", "联合国", ORG),
            ("Kofi Annan", "科菲·安南", "Ghana")]),
    2002: ("for his decades of untiring effort to find peaceful solutions to international conflicts, to advance democracy and human rights, and to promote economic and social development.",
           "表彰他数十年来不知疲倦地寻求国际冲突的和平解决方案、推进民主与人权、促进经济与社会发展",
           [("Jimmy Carter", "吉米·卡特", US)]),
    2003: ("for her efforts for democracy and human rights, focusing especially on the rights of women and children.",
           "表彰她为民主与人权所做的努力，尤其聚焦于妇女与儿童的权利",
           [("Shirin Ebadi", "希琳·伊巴迪", "Iran")]),
    2004: ("for her contribution to sustainable development, democracy and peace.",
           "表彰她对可持续发展、民主与和平的贡献",
           [("Wangari Muta Maathai", "旺加里·马塔伊", "Kenya")]),
    2005: ("for their efforts to prevent nuclear energy from being used for military purposes and to ensure that nuclear energy for peaceful purposes is used in the safest possible way.",
           "表彰他们为防止核能被用于军事目的、并确保和平利用核能以最安全的方式进行所做的努力",
           [("International Atomic Energy Agency", "国际原子能机构", ORG),
            ("Mohamed ElBaradei", "穆罕默德·巴拉迪", "Egypt")]),
    2006: ("for their efforts to create social and economic development from below.",
           "表彰他们自下而上促进社会与经济发展的努力",
           [("Muhammad Yunus", "穆罕默德·尤努斯", "Bangladesh"),
            ("Grameen Bank", "格莱珉银行", "Bangladesh")]),
    2007: ("for their efforts to build up and disseminate greater knowledge about man-made climate change, and to lay the foundations for the measures that are needed to counteract such change.",
           "表彰他们为积累与传播人为气候变化的知识、并为应对此类变化所需的措施奠定基础所做的努力",
           [("Intergovernmental Panel on Climate Change", "政府间气候变化专门委员会", ORG),
            ("Al Gore", "阿尔·戈尔", US)]),
    2008: ("for his important efforts, on several continents and over more than three decades, to resolve international conflicts.",
           "表彰他三十多年来在多个大洲为解决国际冲突所做的重要努力",
           [("Martti Ahtisaari", "马尔蒂·阿赫蒂萨里", "Finland")]),
    2009: ("for his extraordinary efforts to strengthen international diplomacy and cooperation between peoples.",
           "表彰他为加强国际外交与各国人民间合作所做的非凡努力",
           [("Barack Obama", "巴拉克·奥巴马", US)]),
    2010: ("for his long and non-violent struggle for fundamental human rights in China.",
           "表彰他在中国为基本人权而进行的长期非暴力斗争",
           [("Liu Xiaobo", "刘晓波", "China")]),
    2011: ("for their non-violent struggle for the safety of women and for women's rights to full participation in peace-building work.",
           "表彰她们以非暴力方式维护妇女安全、争取妇女充分参与和平建设工作的权利",
           [("Ellen Johnson Sirleaf", "埃伦·约翰逊·瑟利夫", "Liberia"),
            ("Leymah Gbowee", "莱伊曼·古博薇", "Liberia"),
            ("Tawakkol Karman", "塔瓦库勒·卡曼", "Yemen")]),
    2012: ("for over six decades contributed to the advancement of peace and reconciliation, democracy and human rights in Europe.",
           "表彰其六十余年来对推进欧洲和平与和解、民主与人权的贡献",
           [("European Union", "欧洲联盟", ORG)]),
    2013: ("for its extensive efforts to eliminate chemical weapons.",
           "表彰其为消除化学武器所做的广泛努力",
           [("Organisation for the Prohibition of Chemical Weapons", "禁止化学武器组织", ORG)]),
    2014: ("for their struggle against the suppression of children and young people and for the right of all children to education.",
           "表彰他们对抗对儿童与青年的压迫、争取所有儿童受教育权的斗争",
           [("Kailash Satyarthi", "凯拉什·萨蒂亚尔蒂", "India"),
            ("Malala Yousafzai", "马拉拉·优素福扎伊", "Pakistan")]),
    2015: ("for its decisive contribution to the building of a pluralistic democracy in Tunisia in the wake of the Jasmine Revolution of 2011.",
           "表彰其在 2011 年茉莉花革命后为突尼斯建设多元民主做出的决定性贡献",
           [("Tunisian National Dialogue Quartet", "突尼斯全国对话四方机制", "Tunisia")]),
    2016: ("for his resolute efforts to bring the country's more than 50-year-long civil war to an end.",
           "表彰他坚定不移地结束该国长达 50 余年的内战",
           [("Juan Manuel Santos", "胡安·曼努埃尔·桑托斯", "Colombia")]),
    2017: ("for its work to draw attention to the catastrophic humanitarian consequences of any use of nuclear weapons and for its ground-breaking efforts to achieve a treaty-based prohibition of such weapons.",
           "表彰其唤起世人关注任何使用核武器行为的人道主义灾难性后果，并开创性地推动以条约禁绝此类武器",
           [("International Campaign to Abolish Nuclear Weapons", "国际废除核武器运动", ORG)]),
    2018: ("for their efforts to end the use of sexual violence as a weapon of war and armed conflict.",
           "表彰他们为终结在战争与武装冲突中将性暴力用作武器所做的努力",
           [("Denis Mukwege", "德尼·穆奎格", "Democratic Republic of the Congo"),
            ("Nadia Murad", "纳迪娅·穆拉德", "Iraq")]),
    2019: ("for his efforts to achieve peace and international cooperation, and in particular for his decisive initiative to resolve the border conflict with neighbouring Eritrea.",
           "表彰他为实现和平与国际合作所做的努力，尤其是为解决与邻国厄立特里亚边界冲突采取的决定性行动",
           [("Abiy Ahmed", "阿比·艾哈迈德", "Ethiopia")]),
    2020: ("for its efforts to combat hunger, for its contribution to bettering conditions for peace in conflict-affected areas and for acting as a driving force in efforts to prevent the use of hunger as a weapon of war and conflict.",
           "表彰其为战胜饥饿所做的努力、对改善冲突地区和平条件的贡献，以及在防止将饥饿用作战争与冲突武器方面的推动作用",
           [("World Food Programme", "世界粮食计划署", ORG)]),
    2021: ("for their efforts to safeguard freedom of expression, which is a precondition for democracy and lasting peace.",
           "表彰他们为捍卫言论自由所做的努力——言论自由是民主与持久和平的前提条件",
           [("Maria Ressa", "玛丽亚·雷萨", "Philippines"),
            ("Dmitry Muratov", "德米特里·穆拉托夫", "Russia")]),
    2022: ("The Peace Prize laureates represent civil society in their home countries. They have for many years promoted the right to criticise power and protect the fundamental rights of citizens. They have made an outstanding effort to document war crimes, human right abuses and the abuse of power. Together they demonstrate the significance of civil society for peace and democracy.",
           "本届和平奖得主是其母国民间社会的代表。他们多年来倡导批评权力的权利、维护公民的基本权利，并为记录战争罪行、侵犯人权与滥用权力做出了杰出努力。他们共同彰显了民间社会对和平与民主的重要意义。",
           [("Ales Bialiatski", "阿列斯·比亚利亚茨基", "Belarus"),
            ("Memorial", "纪念人权组织", "Russia"),
            ("Centre for Civil Liberties", "公民自由中心", "Ukraine")]),
    2023: ("for her fight against the oppression of women in Iran and her fight to promote human rights and freedom for all.",
           "表彰她对抗伊朗对妇女的压迫、为促进所有人的人权与自由而进行的斗争",
           [("Narges Mohammadi", "纳尔格斯·穆罕默迪", "Iran")]),
    2024: ("for its efforts to achieve a world free of nuclear weapons and for demonstrating through witness testimony that nuclear weapons must never be used again.",
           "表彰其为实现无核武器世界所做的努力，以及通过亲历者证言昭示核武器绝不应再次被使用",
           [("Nihon Hidankyo", "日本原水爆被害者团体协议会（日本被团协）", "Japan")]),
    2025: ("for her tireless work promoting democratic rights for the people of Venezuela and for her struggle to achieve a just and peaceful transition from dictatorship to democracy.",
           "表彰她不知疲倦地促进委内瑞拉人民的民主权利，并为实现从专制到民主的公正和平过渡而斗争",
           [("María Corina Machado", "玛丽亚·科里娜·马查多", "Venezuela")]),
}
