#!/usr/bin/env python3
"""
为 tex/<Name>/ 创建对应的 tex/<Name>_zh/ 中文翻译目录骨架。

骨架内容：
  - 复制 images/（共享同一份图片）→ 用 symlink 节省磁盘
  - 复制 Makefile（修改 NAME 为 <Name>_zh）
  - 复制 body.tex 和 metadata.tex（待人工/翻译脚本逐步替换为中文）
  - 创建 <Name>_zh.tex：引用 ../common/preamble_zh.tex

并把 common/preamble_zh.tex 同步到 tex/common/。

用法：
  python make_zh_skeleton.py             # 处理 tex/ 下所有原始（非 _zh）目录
  python make_zh_skeleton.py --only Gauss
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TEX = ROOT / "tex"
COMMON_SRC = ROOT / "common"
COMMON_DST = TEX / "common"

MAIN_ZH_TEMPLATE = r"""% Auto-generated 中文版主文件。Edit common/preamble_zh.tex for global style.
\input{../common/preamble_zh.tex}
\input{metadata.tex}

\title{\MathematicianName}
\author{}
\date{\MathematicianBirth\ \textendash\ \MathematicianDeath}

\begin{document}

\maketitle

\begin{abstract}
\noindent \MathematicianDescription
\end{abstract}

\InfoBox

\vspace{1em}
\hrule
\vspace{1em}

\input{body.tex}

\end{document}
"""

SUB_MAKEFILE = r"""# Auto-generated 中文版 per-person Makefile.
NAME := {name}
TEX  := $(NAME).tex
PDF  := $(NAME).pdf

.PHONY: all pdf build clean distclean

all: pdf

build: $(PDF)

pdf: $(PDF)
	@$(MAKE) --no-print-directory clean

$(PDF): $(TEX) body.tex metadata.tex ../common/preamble_zh.tex
	latexmk -xelatex -interaction=nonstopmode -halt-on-error $(TEX)

clean:
	@latexmk -c $(TEX) >/dev/null 2>&1 || true
	@rm -f *.aux *.log *.out *.toc *.fls *.fdb_latexmk *.synctex.gz *.xdv

distclean: clean
	rm -f $(PDF)
"""


def make_skeleton(src_dir: Path) -> Path:
    name = src_dir.name
    zh_name = f"{name}_zh"
    zh_dir = TEX / zh_name
    zh_dir.mkdir(exist_ok=True)

    # 1) 主 tex
    (zh_dir / f"{zh_name}.tex").write_text(MAIN_ZH_TEMPLATE, encoding="utf-8")

    # 2) Makefile
    (zh_dir / "Makefile").write_text(SUB_MAKEFILE.format(name=zh_name), encoding="utf-8")

    # 3) body.tex / metadata.tex：先复制原文，后续手动翻译
    for f in ("body.tex", "metadata.tex"):
        src = src_dir / f
        dst = zh_dir / f
        if src.exists() and not dst.exists():
            shutil.copy2(src, dst)

    # 4) images：用 symlink 共享原图，节省磁盘
    img_src = src_dir / "images"
    img_link = zh_dir / "images"
    if img_src.exists() and not img_link.exists():
        img_link.symlink_to(f"../{name}/images")

    return zh_dir


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", help="仅处理名字含此子串的目录")
    args = ap.parse_args()

    # 同步中文 preamble 到 tex/common/
    COMMON_DST.mkdir(parents=True, exist_ok=True)
    src_p = COMMON_SRC / "preamble_zh.tex"
    if src_p.exists():
        (COMMON_DST / "preamble_zh.tex").write_text(
            src_p.read_text(encoding="utf-8"), encoding="utf-8"
        )

    # 收集所有原始（非 _zh、非 common）目录
    src_dirs = sorted(
        p for p in TEX.iterdir()
        if p.is_dir() and p.name != "common" and not p.name.endswith("_zh")
    )
    if args.only:
        src_dirs = [d for d in src_dirs if args.only.lower() in d.name.lower()]

    print(f"将创建 {len(src_dirs)} 个 _zh 骨架")
    created = []
    for d in src_dirs:
        zh = make_skeleton(d)
        print(f"  ✓ {zh.relative_to(TEX)}")
        created.append(zh.name)

    # 更新顶层 Makefile，把所有目录（含 _zh）都加进去
    all_subs = sorted(
        p.name for p in TEX.iterdir()
        if p.is_dir() and p.name != "common"
    )
    update_top_makefile(all_subs)
    print(f"\n顶层 Makefile 已更新，共 {len(all_subs)} 个子目录")
    return 0


def update_top_makefile(subdirs: list[str]) -> None:
    head = f"""# Top-level Makefile for all mathematicians (中英双语).
# Auto-generated by make_zh_skeleton.py.

SUBDIRS := {' '.join(subdirs)}
EN_SUBDIRS := {' '.join(d for d in subdirs if not d.endswith('_zh'))}
ZH_SUBDIRS := {' '.join(d for d in subdirs if d.endswith('_zh'))}

.PHONY: all en zh build clean distclean parallel {' '.join(subdirs)}

all:
\t@for d in $(SUBDIRS); do \\
\t  echo "==> $$d"; \\
\t  $(MAKE) -C $$d pdf || exit $$?; \\
\tdone
\t@echo "✅ 全部完成。仅保留各子目录下的 PDF。"

en:
\t@for d in $(EN_SUBDIRS); do echo "==> $$d"; $(MAKE) -C $$d pdf || exit $$?; done

zh:
\t@for d in $(ZH_SUBDIRS); do echo "==> $$d"; $(MAKE) -C $$d pdf || exit $$?; done

build:
\t@for d in $(SUBDIRS); do echo "==> $$d"; $(MAKE) -C $$d build || exit $$?; done

clean:
\t@for d in $(SUBDIRS); do $(MAKE) -C $$d clean; done

distclean:
\t@for d in $(SUBDIRS); do $(MAKE) -C $$d distclean; done

parallel:
\t$(MAKE) -j $$(sysctl -n hw.ncpu 2>/dev/null || echo 4) all
"""
    lines = [head, ""]
    for d in subdirs:
        target_name = "pdf"
        lines.append(f"{d}:\n\t$(MAKE) -C {d} {target_name}\n")
    (TEX / "Makefile").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
